<?php 
	$url_new = $this->url(array('module'=>'product','controller'=>'index','action'=>'add',));
	$url_edit = $this->url(array('module'=>'product','controller'=>'index','action'=>'edit',));
	$url_delete = $this->url(array('module'=>'product','controller'=>'index','action'=>'delete',));
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$formFilter = $this->formFilter;
	$rs = $this->product;
?>
<title><?php echo $tr->translate("PRODUCT");?></title>
<div class="row">
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-globe"></i><?php echo $tr->translate("PRODUCT_LIST");?>
				</div>
				<a href="<?php echo $url_new;?>" class="btn btn-bg blue  pull-right">
					<i class="fa fa-plus"></i>&nbsp;<?php echo $tr->translate("ADD_NEW");?>
				</a>
			</div>
			<div class="portlet-body form frmfilter">
				<form method="post" action="<?php echo $formFilter->getAction(); ?>">
					<div class="form-group">
							<label class="control-label col-md-3">
								<?php echo $formFilter->getElement('ad_search');?>
							</label>
							<label class="control-label col-md-3">
								<?php echo $formFilter->getElement('branch');?>
							</label>
							<label class="control-label col-md-3">
								<?php echo $formFilter->getElement('brand');?>
							</label>
							<label class="control-label col-md-3">
								<?php echo $formFilter->getElement('category');?>
							</label>
						</div>
						<div class="form-group">
							<label class="control-label col-md-3">
								<?php echo $formFilter->getElement('model');?>
							</label>
							<label class="control-label col-md-3">
								<?php echo $formFilter->getElement('color');?>
							</label>
							<label class="control-label col-md-3">
								<?php echo $formFilter->getElement('status');?>
							</label>
							<label class="control-label col-md-3">
								<button class="btn btn-primary col-md-12" value="" ><i class="fa fa-save"></i>&nbsp;<?php echo $tr->translate("REFRESH");?></button>
							</label>
						</div>				
				</form> 
				<div class="contain_form" style="clear: both;">
				<?php 
				$stringPagination = '<script type="text/javascript">
				$(document).ready(function(){
				$("#table").tablesorter();
				$("#table").tablesorter().tablesorterPager({container: $("#pagination_table"),size:15});
				$("#pagedisplay").focus(function(){ this.blur();
				});
				});
				</script>
				<div id="pagination_table" class="pager" >
				<form >
				<table  style="width: 200px;"><tr>
				<td><img src="'.$this->baseUrl().'/images/first.gif" class="first"/></td>
				<td><img src="'.$this->baseUrl().'/images/previous.gif" class="prev"/></td>
				<td><input id="pagedisplay" type="text" class="pagedisplay"/></td>
				<td><img src="'.$this->baseUrl().'/images/next.gif" class="next"/></td>
				<td><img src="'.$this->baseUrl().'/images/last.gif" class="last"/></td>
				<td><select class="pagesize" >
				<option   value="10">10</option>
				<option selected="selected"  value="15">15</option>
				<option value="20">20</option>
				<option value="30">30</option>
				<option value="40">40</option>
				<option value="50">50</option>
				<option value="60">60</option>
				<option value="70">70</option>
				<option value="80">80</option>
				<option value="90">90</option>
				<option value="100">100</option>
				</select>
				</td>
				</tr>
				</table>
				</form>
				</div>	';
				?>
				<form name="list">
					<div style="overflow:scroll; max-height: 450px; overflow-x:hidden;" >
						<table class="collape tablesorter" id="table" width="100%">
							<thead>
								<tr>
									<th class="tdheader"><?php echo $tr->translate("NUM");?></th>
									<th class="tdheader"><?php echo $tr->translate("BRANCH_NAME");?></th>
									<th class="tdheader"><?php echo $tr->translate("PHOTO");?></th>
									<th class="tdheader"><?php echo $tr->translate("ITEM_CODE");?></th>
									<th class="tdheader"><?php echo $tr->translate("ITEM_NAME");?></th>
									<th class="tdheader"><?php echo $tr->translate("PRODUCT_CATEGORY");?></th>
									<th class="tdheader"><?php echo $tr->translate("MEASURE");?></th>
									<th class="tdheader"><?php echo $tr->translate("QTY");?></th>
									<th class="tdheader"><?php echo $tr->translate("COST_PRICE");?></th>
									<th class="tdheader"><?php echo $tr->translate("USER");?></th>
									<th class="tdheader"><?php echo $tr->translate("STATUS");?></th>
								</tr>
							</thead>
							<tbody>
								<?php 
								$r=0;
								if (!empty($this->row)) foreach ($this->row as $rs){
									if($r%2==0){$attb='normal';}else{ $attb='alternate';}
									$r++;
									$images = $this->baseUrl().'/images/no_images.jpg';
									if (!empty($rs["photo"])){
										if (file_exists(PUBLIC_PATH.'/images/proimage/'.$rs["photo"])) {
											$images = $this->baseUrl().'/images/proimage/'.$rs['photo'];
										}
									}
								?>
								<tr class="<?php echo $attb; ?>">
									<td class="items-no"><?php echo $r;?></td>
									<td class="items">&nbsp;<img style="width: 70px;height: 35px;" src="<?php echo $images;?>" />&nbsp;</td>
									<td class="items">&nbsp;<a href="<?php echo $this->baseUrl()."/product/index/edit/id/".$rs['id'];?>"><?php echo $rs['branch'];?></a>&nbsp;</td>
									<td class="items">&nbsp;<a href="<?php echo $this->baseUrl()."/product/index/edit/id/".$rs['id'];?>"><?php echo $rs['item_code'];?></a>&nbsp;</td>
									<td class="items">&nbsp;<a href="<?php echo $this->baseUrl()."/product/index/edit/id/".$rs['id'];?>"><?php echo $rs['item_name'];?></a>&nbsp;</td>
									<td class="items">&nbsp;<?php echo $rs['cat'];?>&nbsp;</td>
									<td class="items">&nbsp;<?php echo $rs['measure'];?>&nbsp;</td>
									<td class="items" align="center">&nbsp;<?php echo $rs['qty'];?>&nbsp;</td>
									<td class="items" align="right">&nbsp;<?php echo $rs['price'];?>&nbsp;</td>
									<td class="items" align="center">&nbsp;<?php echo $rs['user_name'];?>&nbsp;</td>
									<td class="items" align="center">&nbsp;<?php echo $rs['status'];?>&nbsp;</td>
								</tr>
								<?php }?>
							</tbody>
						</table>
						<?php $counter='<span class="row_num">'.$tr->translate('NUM-RECORD').count($this->row).'</span>';?>
						<div class="footer_list"><?php echo $stringPagination.$counter;?></div>
					</div>
				</form>
						<?php //echo $this->list; ?>
			    </div>
		   </div>
		</div>
	</div>
</div>






















