<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
?>
<title><?php echo $tr->translate("TRANSFER_STOCK");?></title>
<?php 
	$url_new = $this->url(array('module'=>'product','controller'=>'transferstock','action'=>'add',));
	//$url_delete = $this->url(array('module'=>'product','controller'=>'index','action'=>'delete-product',));
	$formFilter = $this->formFilter;
?>
<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-globe"></i><?php echo $tr->translate("TRANSFER_STOCK");?>
				</div>
				<div class="caption pull-right">
					<a href="<?php echo $url_new;?>" class="btn btn-bg blue  ">
						<i class="fa fa-plus"></i>&nbsp;<?php echo $tr->translate("ADD_NEW");?>
					</a>
				</div>
			</div>
		<div class="portlet-body form">
			<form class="form-horizontal" method="post" action="" >
				<div class="form-body">
							<div class="form-group">
								<div class="col-md-3">
									<?php echo $formFilter->getElement('ad_search');?>
								</div>
								<div class="col-md-3">
									<?php echo $formFilter->getElement('start_date');?>
								</div>
								<div class="col-md-3">
									<?php echo $formFilter->getElement('end_date');?>
								</div>
								<div class="col-md-3">
									<button class="btn btn-primary col-md-12" value="" ><i class="fa fa-save"></i>&nbsp;<?php echo $tr->translate("REFRESH");?></button>
								</div>
							</div>		
				</div>
			</form>
			
		</div>
	<div style="position: relative; clear: both;">
		<div class="contain_form">
			<?php //echo $this->list; ?>
		</div>
		
		<div style="overflow:scroll; max-height: 450px; overflow-x:hidden;" >
		<table class="collape tablesorter" id="'.$id.'" width="100%">
		<thead>
		<tr>   
			<th class="tdheader">AAA</th>
			<th class="tdheader">AAA</th>
			<th class="tdheader">AAA</th>
		</tr>
		
		</thead>
		<tr class="alternate">
		<td>AA</td>
		<td>BB</td>
		<td>BB</td>
		</tr>
		      
		</table>
		</div>
		
	</div>
</div><!-- end .right -->

