<?php
$this->headTitle('Registration | log in page'); 
echo $this->headTitle();
$tr=Application_Form_FrmLanguages::getCurrentlanguage();
$base_url = $this->baseUrl();
?>
<!DOCTYPE HTML> 
<html>
<head>
<style> .red{color:red;}</style>
<?php /*
*/?>
<script src="<?php echo $base_url;?>/js/dojo-1.6.1/dojo/dojo.js"  djConfig="isDebug: true,parseOnLoad: true"></script>
<link rel="stylesheet" type="text/css" href="<?php echo $base_url;?>/js/dojo-1.6.1/dijit/themes/tundra/tundra.css"/>
<link href="<?php echo $this->baseUrl()?>/assets/global/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css"/>
	
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<style type="text/css">
	.btn{
		height: 40px;
		min-width: 100px;	
	}
.fullside {
		    width: 99%;
		    height: 30px;
		}
		.dijitArrowButtonInner, .dijitIconSearch {
		    margin-top: 6px !important;
		}
		.dijitTextBox, .dijitValidationTextBox, .dijitInputField, .dijitInputContainer, .dijitInputInner, dijitReset, .dijitRight, .dijitButtonNode, .dijitArrowButton, .dijitDownArrowButton, .dijitArrowButtonContainer {
		    height: 30px;
		}
		.tundra .dijitButtonText {
		    line-height: 24px;
		}
		.tundra .dijitInputContainer INPUT, .tundra .dijitTextBox {
		    color: #000000;
		    font-size: 16px;
		}
		.btn{
			height: 40px;
			min-width: 100px;	
		}
		.f_style{
			font-family:'NiDA Khmer Empire';
		    font-size:14px;
			text-shadow: 1px 1px 1px #0B404A;
		}
		.t_shadow{ text-shadow: 1px 1px 1px #0B404A;}
.container {
    padding: 0;
    width: auto;
}
.login-page .header-top {
    background: #02014a;
    color: #fff;
    padding: 10px 0;
    min-height: 10%;
    border-bottom: solid 4px #0077c5;
}
.login-page .content {
    min-height: 65%;
    padding: 60px 0;
}
.login-page .content .login-form {
    padding: 20px;
    background: #02014a;
    color: #fff;
    margin-top: 30px;
    box-shadow: 3px 5px 5px #9e9e9e;
}
.form-group {
    margin-bottom: 3px;
    display: flow-root;
    clear: both;
}
.login-page .footer {
    background: #02014a;
    border-top: solid 4px #0077c5;
    min-height: 15%;
    color: #fff;
    padding: 10px 0;
}
.login-page .footer .contact_info ul {
    list-style-type: none;
    padding: 0;
    line-height: 25px;
    font-size: 14px;
}
.login-page .system-title {
    font-size: 18px;
    font-family: 'Khmer MEF2';
    line-height: 30px;
}
label.control-label {
    margin-top: 6px;
    margin-bottom: 0;
    vertical-align: bottom;
    padding: 0;
    font-size: 13px;
    font-weight: 700;
}
.login-page .footer .contact_info a.copyright {
    color: #089dff;
    cursor: pointer;
}
body {
    font-family: Arial,Helvetica, sans-serif,'Times New Roman','Kh Battambang','Khmer Battambang';
    font-size: 14px;
}
</style>
<link rel="shortcut icon" type="image/x-icon" href="<?php echo $this->baseUrl();?>/images/icon.ico" />
<script type="text/javascript">	
	dojo.require("dijit.form.ValidationTextBox");
	dojo.require('dijit.form.Form');	
	dojo.require('dijit.form.Button');
</script>
</head>
<body class="tundra" style="background: #edf7ef;" >
	<div class="container ">
    	<div class="main_container login-page">
    		<div class="header-top">
    			<div class="col-md-3 col-sm-3 col-xs-12">
    				<img src="<?php echo $this->baseUrl()."/images/cam-app-logo.png";?>" style="max-height:45px;margin: 0;padding-left: 10px;"  />
    			</div>
    			<div class="col-md-6 col-sm-6 col-xs-12">
    				<div class="system-title text-center">
    				<?php echo $this->data["system_name"];?><br />
					<strong>S</strong>tock <strong> M</strong>anagement <strong>S</strong>ystem
					</div>
    			</div>
    			<div class="col-md-3 col-sm-3 col-xs-12">
    			</div>
    			<div class="clearfix"></div>
    		</div>
    		<div id='marquee' style="margin-top: 5px;">
				<marquee behavior="scroll" direction="left" onmouseout="this.start()" onmouseover="this.stop()" scrollamount="5"><?php //echo $this->data["label_animation"];?></marquee>
			</div>
    		 <div class="content">
    			<div class="col-md-6 col-sm-6 col-xs-12">
    				<div class="imgage-content text-center">
    					<img alt="<?php ?>" src="<?php echo $base_url."/images/stockshow.png";//$base_url.$this->data['logo-path-name']?>">
    				</div>
    			</div>
    			<div class="col-md-1 col-sm-1 col-xs-12">
    			</div>
    			<div class="col-md-5 col-sm-5 col-xs-12">
    				<div class="login-form">
    					<h4 style="font-family: 'Khmer MEF2';"><i class="fa fa-lock" aria-hidden="true"></i> <?php echo $tr->translate("SECURITY_SYSTEM");?>​</h4>
    					<?php if (!empty($this->msg)){?>
    					<span style=" color: #f9ba00; padding: 5px 0;  display: block;  text-shadow: 0px 0px #966d6d;"><?php echo $this->msg;?></span>
    					<?php }?>
    					<form id="frmLogin" dojoType="dijit.form.Form" method="post" action="">
							<script type="dojo/method" event="onSubmit">				
								if(this.validate()) {						
									return true;
								}
								return false;
							</script>
							<div class="form-group login-row">
								 <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name"><?php echo $tr->translate("ACCOUNT_NAME");?>
				                 </label>
			                   	 <div class="col-md-9 col-sm-9 col-xs-12">
			                    	<input class="fullside" type="text" required="true" name="txt_email" id="txt_email" placeholder="ឈ្មោះអ្នកប្រើប្រាស់​" 
									data-dojo-type="dijit/form/ValidationTextBox" missingMessage="សូមបំពេញឈ្មោះអ្នកប្រើប្រាស់! " style="width: 100%;"/>
			                    </div>
							</div>
							<div class="form-group login-row">
								 <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name"><?php echo $tr->translate("PASSWORD");?>
				                 </label>
			                   	 <div class="col-md-9 col-sm-9 col-xs-12">
			                    	<input class="fullside" type="password" required="true" name="txt_password" id="txt_password" placeholder="លេខសំងាត់" 
								data-dojo-type="dijit/form/ValidationTextBox" missingMessage="សូមបំពេញលេខសំងាត់!" style="width: 100%;"/>
			                    </div>
							</div>
							<div class="form-group login-row">
								 <label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name"><?php echo $tr->translate("LANGAUGE");?>
				                 </label>
			                   	 <div class="col-md-9 col-sm-9 col-xs-12">
			                    	<select class="fullside" data-dojo-type="dijit/form/FilteringSelect" name="lang" id="lang" style="width: 150px"  onchange="changeLange();" > 
									<option value="1" <?php if($this->rslang==1){echo"selected";}?>>ខ្មែរ</option> 
									<option value="2" <?php if($this->rslang==2){echo"selected";}?>>English</option> 
								</select>
			                    </div>
							</div>
							<div class="form-group login-row text-center">
							<input class="f_styles" style=" font-weight:bold;	color: #02014a; font-size: 13px;" type="submit" value="ចូលប្រើប្រាស់" label="<?php echo $tr->translate("LOGIN");?>" data-dojo-type="dijit/form/Button" />
								<input class="f_styles" style=" font-weight:bold; color: #02014a; font-size: 13px;" type="reset" value="សំអាត" id="clear_login" data-dojo-type="dijit/form/Button" label="<?php echo $tr->translate("CLEAR");?>" />
							</div>
						</form>
    				</div>
    			</div>
    			<div class="clearfix"></div>
    		</div>
    		
    		<div class="footer">
    			<div class="col-md-5 col-sm-5 col-xs-12">
    				<div class="contact_info">
    					<ul>
    						<li><?php echo $tr->translate("USINGBY")?> : <strong><?php echo $this->data['client_company_name']?></strong></li>
    						<li><?php echo $this->data['branch-add-client']?></li>
    						<li> <?php echo $this->data['tel-client'];?> <?php echo $this->data['email_client']?></li>
    						<li><?php echo $this->data['client_website']?></li>
    					</ul>
    				</div>
    			</div>
    			<div class="col-md-2 col-sm-2 col-xs-12">
    			</div>
    			<div class="col-md-5 col-sm-5 col-xs-12">
    				<div class="contact_info">
    					<ul>
    						<li><strong><?php echo $tr->translate("CONTACT_INFO")?></strong> : </li>
    						<li><?php echo $this->data['branch_add']?></li>
    						<li> <?php echo $this->data['branch-tel'];	?> </li>
    						<li><?php echo $this->data['branch_email']?></li>
    						<li>&copy រក្សាសិទ្ធិគ្រប់យ៉ាង
    						<a title="<?php echo $this->data['power_by']?>" class="copyright" href="http://<?php echo $this->data['website']?>" target="_blank">
								<strong><?php echo $this->data['power_by']?></strong></a>
    						</li>
    					</ul>
    				</div>
    			</div>
    			<div class="clearfix"></div>
    		</div>
    		
		</div>
	</div>
	<script src="<?php echo $this->baseUrl()?>/assets/global/plugins/jquery.min.js" type="text/javascript"></script>
	<script src="<?php echo $this->baseUrl()?>/assets/global/plugins/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
	<script type="text/javascript">
			var url_changelang = '<?php echo $this->url(array('module'=>'default','controller'=>'index','action'=>'changelange'));?> ';
			function changeLange(){
				lang = dijit.byId("lang").get("value");
				dojo.xhrPost({
					url: url_changelang,
				    content :{ 
						    'lange':lang,
					},	
					handleAs:"json",
					load: function(data) {
						location.reload();
					},
					error: function(err) {
					}
				});
			}
	</script>
</body>

</html>