<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
?>
<!DOCTYPE html>
<html lang="en">
<!--<![endif]-->
<!-- BEGIN HEAD -->
<head>
<meta charset="utf-8"/>
<title>Metronic | Pages - User Account</title>
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta content="width=device-width, initial-scale=1.0" name="viewport"/>
<meta http-equiv="Content-type" content="text/html; charset=utf-8">
<meta content="" name="description"/>
<meta content="" name="author"/>
<!-- BEGIN GLOBAL MANDATORY STYLES -->
<link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all" rel="stylesheet" type="text/css"/>
<link href="../../assets/global/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css"/>
<link href="../../assets/global/plugins/simple-line-icons/simple-line-icons.min.css" rel="stylesheet" type="text/css"/>
<link href="../../assets/global/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css"/>
<link href="../../assets/global/plugins/uniform/css/uniform.default.css" rel="stylesheet" type="text/css"/>
<link href="../../assets/global/plugins/bootstrap-switch/css/bootstrap-switch.min.css" rel="stylesheet" type="text/css"/>
<!-- END GLOBAL MANDATORY STYLES -->
<!-- BEGIN PAGE LEVEL STYLES -->
<link href="../../assets/global/plugins/bootstrap-fileinput/bootstrap-fileinput.css" rel="stylesheet" type="text/css"/>
<link href="../../assets/admin/pages/css/profile.css" rel="stylesheet" type="text/css"/>
<link href="../../assets/admin/pages/css/tasks.css" rel="stylesheet" type="text/css"/>
<!-- END PAGE LEVEL STYLES -->
<!-- BEGIN THEME STYLES -->
<link href="../../assets/global/css/components.css" id="style_components" rel="stylesheet" type="text/css"/>
<link href="../../assets/global/css/plugins.css" rel="stylesheet" type="text/css"/>
<link href="../../assets/admin/layout/css/layout.css" rel="stylesheet" type="text/css"/>
<link id="style_color" href="../../assets/admin/layout/css/themes/darkblue.css" rel="stylesheet" type="text/css"/>
<link href="../../assets/admin/layout/css/custom.css" rel="stylesheet" type="text/css"/>
<!-- END THEME STYLES -->
<link rel="shortcut icon" href="favicon.ico"/>
<style>
      button{
		      	color: #FFFFFF;
		        background-color: #44b6ae;
		        border-color: "";
		}
</style>
</head>

<!-- BEGIN CONTAINER -->
			<h3 class="page-title">
			User Account <small> </small>
			</h3>
			
			<!-- END PAGE HEADER-->
			<!-- BEGIN PAGE CONTENT-->
			<div class="row margin-top-20">
				<div class="col-md-12">
					<!-- BEGIN PROFILE SIDEBAR -->
					<div class="profile-sidebar">
						<!-- PORTLET MAIN -->
						<div class="portlet light profile-sidebar-portlet">
							<!-- SIDEBAR USERPIC -->
							<div class="profile-userpic" style="width:130px;height:130px;">
								<img src="<?php echo $this->baseUrl()?>/images/<?php echo $this->rs['photo'];?>" class="img-responsive" alt="No photo profile">
							</div>
							<!-- END SIDEBAR USERPIC -->
							<!-- SIDEBAR USER TITLE -->
							<div class="profile-usertitle">
								<div class="profile-usertitle-name">
									 <?php echo $this->rs['fullname'];?>
								</div>
								<div class="profile-usertitle-job">
									User Type:<?php echo $this->rs['username'];?>
								</div>
							</div>
							<!-- END SIDEBAR USER TITLE -->
							<!-- SIDEBAR BUTTONS 
							<div class="profile-userbuttons">
								<button type="button" class="btn btn-circle green-haze btn-sm">Follow</button>
								<button type="button" class="btn btn-circle btn-danger btn-sm">Message</button>
							</div>-->
							<!-- END SIDEBAR BUTTONS -->
							<!-- SIDEBAR MENU -->
							 
							<!-- END MENU -->
						</div>
						<!-- END PORTLET MAIN -->
						<!-- PORTLET MAIN -->
						
						<!-- END PORTLET MAIN -->
					</div>
					<!-- END BEGIN PROFILE SIDEBAR -->
					<!-- BEGIN PROFILE CONTENT -->
					<form role="form" action="<?php echo $this->baseUrl();?>/rsvacl/index" method="post">
					<div class="profile-content">
						<div class="row">
							<div class="col-md-12">
								<div class="portlet light">
									<div class="portlet-title tabbable-line">
										<div class="caption caption-md">
											<i class="icon-globe theme-font hide"></i>
											<span class="caption-subject font-blue-madison bold uppercase">Profile Account</span>
										</div>
										<ul class="nav nav-tabs">
											<li class="active">
												<a href="#tab_1_1" data-toggle="tab">Personal Info</a>
											</li>
											<li>
												<a href="#tab_1_2" data-toggle="tab">Change Avatar</a>
											</li>
											<li>
												<a href="#tab_1_3" data-toggle="tab">Change Password</a>
											</li>
											<li>
												<a href="#tab_1_4" data-toggle="tab">Privacy Settings</a>
											</li>
										</ul>
									</div>
									<div class="portlet-body">
										<div class="tab-content">
											<!-- PERSONAL INFO TAB -->
											<div class="tab-pane active" id="tab_1_1">
												
												    <input type="hidden" name="id" value="<?php echo $this->rs['user_id'];?>"/> 
													<div class="form-group">
														<label class="col-md-2 control-label">Full Name</label>
														<div class="col-md-4">
														<input type="text" placeholder="John" class="form-control" name="full_name"  id="full_name" value="<?php echo $this->rs['fullname'];?>"/>
														</div>
														<label class="col-md-2 control-label">User Name</label>
														<div class="col-md-4">
														<input type="text" placeholder="Doe" class="form-control" name="user_name"  id="user_name" value="<?php echo $this->rs['username'];?>"/>
														</div>
													</div>
													<div class="form-group">
														<label class="control-label">DOB</label>
														<input type="text" placeholder="dd/mm/yyyy" class="form-control date-picker"  name="dob"  id="dob" value="<?php echo $this->rs['dob'];?>"/>
													</div>
													<div class="form-group">
														<label class="control-label">Mobile Number</label>
														<input type="text" placeholder="855" class="form-control" name="phone"  id="phone" value="<?php echo $this->rs['phone'];?>"/>
													</div>
													<div class="form-group">
														<label class="control-label">Email</label>
														<input type="text" placeholder="Email" class="form-control" name="email"  id="email" value="<?php echo $this->rs['email'];?>"/>
													</div>
													<div class="form-group">
														<label class="control-label">POB</label>
														<input type="text" placeholder="pob" class="form-control"  name="pob"  id="pob" value="<?php echo $this->rs['pob'];?>"/>
													</div>
													<div class="form-group">
														<label class="control-label">Description</label>
														<textarea class="form-control" rows="3" placeholder="dob"  name="descript"  id="descript"  ><?php echo $this->rs['decription'];?></textarea>
													</div>
													<div class="margiv-top-10">
														<button type="submit" name="saveclose" value="saveclose" class="btn btn-primary" ><i class="glyphicon glyphicon-log-in"></i> <?php echo $tr->translate("SAVE_CLOSE")?></button>
														<a href="<?php echo $this->baseUrl();?>/rsvacl/user" class="btn default">
														Cancel </a>
													</div>
												</form>
											</div>
											<!-- END PERSONAL INFO TAB -->
											<!-- CHANGE AVATAR TAB -->
											<div class="tab-pane" id="tab_1_2">
												<p>
													<!-- Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod.
												      --> 
												</p>
												<form action="<?php echo $this->baseUrl();?>/rsvacl/index" role="form" enctype="multipart/form-data" method="post">
													<input type="hidden" name="id" value="<?php echo $this->rs['user_id'];?>"/> 
													<input type="hidden" name="old_pic" value="<?php echo $this->rs['photo'];?>"/> 
													<input type="hidden" placeholder="Doe" class="form-control" name="olde_user_name"  id="olde_user_name" value="<?php echo $this->rs['username'];?>"/>
													<div class="form-group">
														<div class="fileinput fileinput-new" data-provides="fileinput">
															<div class="fileinput-new thumbnail" style="width: 200px; height: 150px;">
															<?php if(!empty($this->rs['photo'])){?>
																<img src="<?php echo $this->baseUrl()?>/images/<?php echo $this->rs['photo'];?> " alt="No photo"/>
																<input type="hidden" name="odl_pic" value="<?php echo $this->rs['photo']; ?>" />
															<?php }else{?>
															<img src="http://www.placehold.it/200x150/EFEFEF/AAAAAA&amp;text=no+image" alt="No photo"/>
															<?php }?>
															</div>
															<div class="fileinput-preview fileinput-exists thumbnail" style="max-width: 200px; max-height: 150px;">
															</div>
															<div>
																<?php 
																	 $frm=$this->frm_pic;
																	?>
																<?php echo $frm->getElement('pic');?>
																<a href="javascript:;" class="btn default fileinput-exists" data-dismiss="fileinput">
																Remove </a>
															</div>
														</div>
													</div>
													<div class="margin-top-10">
														 <button type="submit" name="saveclose" value="saveclose" class="btn btn-primary" ><i class="glyphicon glyphicon-log-in"></i> <?php echo $tr->translate("SAVE_CLOSE")?></button>
														 <a href="<?php echo $this->baseUrl();?>/rsvacl/user" class="btn default">
														 Cancel </a>
													</div>
												</form>
											</div>
											<!-- END CHANGE AVATAR TAB -->
											<!-- CHANGE PASSWORD TAB -->
											<div class="tab-pane" id="tab_1_3">
												<form action="<?php echo $this->baseUrl();?>/rsvacl/index" method="post">
												<input type="hidden" name="id" value="<?php echo $this->rs['user_id'];?>"/> 
													<div class="form-group">
														<label class="control-label">Current Password</label>
														<input type="password" class="form-control" name="old_password" id="old_password"/>
													</div>
													<div class="form-group">
														<label class="control-label">New Password</label>
														<input type="password" class="form-control" name="password" id="password"/>
													</div>
													<div class="form-group">
														<label class="control-label">Re-type New Password</label>
														<input type="password" class="form-control" name="confirm_password" id="confirm_password"/>
													</div>
													<div class="margin-top-10">
														<button type="submit" name="saveclose" value="saveclose" class="btn btn-primary" ><i class="glyphicon glyphicon-log-in"></i> <?php echo $tr->translate("SAVE_CLOSE")?></button>
														<a href="<?php echo $this->baseUrl();?>/rsvacl/user" class="btn default">
														Cancel </a>
													</div>
												</form>
											</div>
											<!-- END CHANGE PASSWORD TAB -->
											<!-- PRIVACY SETTINGS TAB -->
											<div class="tab-pane" id="tab_1_4">
												<form action="#">
												<input type="hidden" name="id" value="<?php echo $this->rs['user_id'];?>"/> 
												<!--  	<table class="table table-light table-hover">
													<tr>
														<td>
															 Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus..
														</td>
														<td>
															<label class="uniform-inline">
															<input type="radio" name="optionsRadios1" value="option1"/>
															Yes </label>
															<label class="uniform-inline">
															<input type="radio" name="optionsRadios1" value="option2" checked/>
															No </label>
														</td>
													</tr>
													<tr>
														<td>
															 Enim eiusmod high life accusamus terry richardson ad squid wolf moon
														</td>
														<td>
															<label class="uniform-inline">
															<input type="checkbox" value=""/> Yes </label>
														</td>
													</tr>
													<tr>
														<td>
															 Enim eiusmod high life accusamus terry richardson ad squid wolf moon
														</td>
														<td>
															<label class="uniform-inline">
															<input type="checkbox" value=""/> Yes </label>
														</td>
													</tr>
													<tr>
														<td>
															 Enim eiusmod high life accusamus terry richardson ad squid wolf moon
														</td>
														<td>
															<label class="uniform-inline">
															<input type="checkbox" value=""/> Yes </label>
														</td>
													</tr>
													</table>-->
													<!--end profile-settings-->
													<div class="margin-top-10">
														<a href="javascript:;" class="btn green-haze">
														Save Changes </a>
														<a href="javascript:;" class="btn default">
														Cancel </a>
													</div>
													
											</div>
											<!-- END PRIVACY SETTINGS TAB -->
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
					</form>
					<!-- END PROFILE CONTENT -->
				</div>
			</div>
			<!-- END PAGE CONTENT-->
</html>