
<?php 
$baseurl = Zend_Controller_Front::getInstance()->getBaseUrl();//new
$url_new =  $this->url(array('module'=>'product','controller'=>'staff','action'=>'index'));
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$row=$this->row;
 
?>
<title><?php echo $tr->translate("ADD_CUSTOMER");?></title>
<div class="row">
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="icon-home"></i><?php echo $tr->translate("ADD_STAFF");?>
				</div>
				<div class="caption pull-right">
					<a href="<?php echo $url_new;?>" class="btn btn-bg blue  ">
						<i class="fa fa-undo"></i>&nbsp;<?php echo $tr->translate("GO_BACK");?>
					</a>
				</div>
			</div>
			<div class="portlet-body form">
				<form id="frm" action="" class="form-horizontal" enctype="multipart/form-data" method="post">
				<div class="form-body">						
						<div class="form-group">
							<label class="control-label col-md-2"><?php echo $tr->translate("EMPLOYEE_NAME");?>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<input type="text" name="staff_name" id="staff_name" value="<?php echo $row['staff_name'];?>" class="validate[required] form-control" placeholder="Employee Name">
								</div>
							</div>
							<label class="control-label col-md-2"><?php echo $tr->translate("STAFF_NO");?> <span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<input type="text" name="staff_no" id="staff_no" value="<?php echo $row['staff_no'];?>" class="form-control" placeholder="ID" readOnly="readonly">	
								</div>
							</div>
						</div>
					<div class="form-group">
							<label class="control-label col-md-2">
							<?php echo $tr->translate("SEX");?><span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<select name="txt_sex" id="txt_sex" OnChange="AddLocation()" class="form-control select2me">
									    <option value="1" <?php if($row['sex']==1) echo 'selected="selected"'?>><?php echo $tr->translate("MALE");?></option>
									    <option value="2" <?php if($row['sex']==2) echo 'selected="selected"'?>><?php echo $tr->translate("FEMALE");?></option>
									</select>
								</div>
							</div>
							<label class="control-label col-md-2">
							<?php echo $tr->translate("CAR_NUMBER");?><span class="required"></span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<input type="text" name="car_number" id="car_number" value="<?php echo $row['car_number'];?>" placeholder="Car Charger" class="form-control">
								</div>
							</div>
					</div>
					<div class="form-group">
						<label class="control-label col-md-2"><?php echo $tr->translate("PHONE");?><span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<input type="text" name="phone" id="phone" value="<?php echo $row['phone'];?>" placeholder="Phone Number" class="form-control">
								</div>
							</div>	
						<label class="control-label col-md-2">
							<?php echo $tr->translate("STAFF_POSITION");?><span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<select name="staff_position" id="staff_position"  class="form-control select2me">
									    <option value=""><?php echo $tr->translate("SELECT_POSITION");?></option>
									    <?php if(!empty($this->staff_pos)) foreach ($this->staff_pos As $rs){?>
									    <option value="<?php echo $rs['id'] ?>" <?php if($row['position_id']== $rs['id']) echo "selected='selected'";?>><?php echo $rs['name'] ?></option>
									   <?php }?>
									</select>
								</div>	 
							</div>
					</div>				
					<div class="form-group">
							<label class="control-label col-md-2">
								<?php echo $tr->translate("PLACE_OF_BIRTH");?><span class="required">
									</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<textarea name="pob" id="pob" placeholder="Place Of Birth" class="form-control" rows="3" cols="80"><?php echo $row['pob'];?></textarea>
								</div>
							</div>
							
						    <label class="control-label col-md-2">
								<?php echo $tr->translate("NOTE");?><span class="required">
									</span>
							</label>
							<div class="col-md-4">
									<div class="input-icon right">
										<i class="fa"></i>
										<textarea name="note" id="note" placeholder="Notice" class="form-control" rows="3" cols="80"><?php echo $row['note'];?></textarea>
									</div>
							</div>
					</div>
					<div class="form-group">
							<label class="control-label col-md-2">
								<?php //echo $tr->translate("PLACE_OF_BIRTH");?><span class="required">
									</span>
							</label>
							<div class="col-md-4">
							</div>
							
						    <label class="control-label col-md-2">
								<?php echo $tr->translate("STATUS");?><span class="required">
									</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<select name="status" id="status"  class="form-control select2me">
									    <option value="1" <?php if($row['status']== 1) echo "selected='selected'";?>>Active</option>
									    <option value="2" <?php if($row['status']== 2) echo "selected='selected'";?>>Deactive</option>
									</select>
								</div>	 
							</div>
					</div>
					<div class="form-group">
						<div class="form-group">
							<div class="col-md-3"></div>
							<div class="col-md-2">
								<a href="<?php echo $this->baseUrl();?>/product/staff"><button type="button" class="btn red btn-block btn-lg"><i class="fa fa-times"></i> <?php echo $tr->translate("GO_BACK")?></button></a>
							</div>
							<div class="col-md-2">
								<div class="input-icon right">
									<button type="submit" name="saveclose" value="saveclose" class="btn blue btn-block btn-lg" ><i class="fa fa-close"></i> <?php echo $tr->translate("SAVE_CLOSE")?></button>
								</div>
							</div>
							<div class="col-md-3"></div>
						</div>
					</div>
				</div>
				</form>
			</div>
		</div>
	</div>
</div>
</body>
</html>
 <script>
 $(document).ready(function() {
});

$('#frm').submit(function() {
	customer_id=$("#customer_type").val();
	if(customer_id=='' || customer_id==-1){
		alert("Please select customer type");
		$('#customer_type').select2('open');
		return false;	
	}
	identity =$("#identity").val();
	if(identity=='' || identity==-1){
		alert("Please add product row");
		$('#add_item').select2('open');
		return false;
	}
});
</script>