<?php 					
	$url_new = $this->url(array('module'=>'purchase','controller'=>'index','action'=>'add',));
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$formFilter = $this->formFilter;
	//print_r($this->rs);
?>
<title><?php echo $tr->translate("CHECK_APPROVE");?></title>
<meta charset="utf-8" />
<div class="row">
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-globe"></i><?php echo $tr->translate("CHECK_APPROVE");?>
				</div>
				<!--<a href="<?php echo $url_new;?>" class="btn btn-sm green  pull-right">
					<i class="fa fa-plus"></i>&nbsp;<?php //echo $tr->translate("ADD_NEW");?>
				</a>-->
			</div>
			<div class="portlet-body form frmfilter">
				<form class="form-horizontal" method="post" action="" >
				<div class="form-body">
							<div class="form-group">
								<div class="col-md-3">
									<?php echo $formFilter->getElement('ad_search');?>
								</div>
								<div class="col-md-3">
									<?php echo $formFilter->getElement('branch');?>
								</div>
								<div class="col-md-3">
									<?php echo $formFilter->getElement('start_date');?>
								</div>
								<div class="col-md-3">
									<?php echo $formFilter->getElement('end_date');?>
								</div>
							</div>		
							<div class="form-group">
								<div class="col-md-3">
									<button class="btn btn-primary col-md-12" value="" ><i class="fa fa-save"></i>&nbsp;<?php echo $tr->translate("REFRESH");?></button>
								</div>
							</div>		
					</div>
				</form>
				<div class="contain_form" style="clear: both;">
					<form name="list"><div style="overflow:scroll; max-height: 450px; overflow-x:hidden;" >
					<table class="collape tablesorter" id="table" width="100%">
						<thead>
							<tr>
								<th class="tdheader"><?php echo  $tr->translate("NUM");?></th>
								<th class="tdheader"><?php echo  $tr->translate("TRANSFER_NO");?></th>
								<th class="tdheader"><?php echo  $tr->translate("TRANSFER_DATE");?></th>
								<th class="tdheader"><?php echo  $tr->translate("FROM_LOCATION");?></th>
								<th class="tdheader"><?php echo  $tr->translate("TO_LOCATION");?></th>
								<th class="tdheader"><?php echo  $tr->translate("TOTAL_QTY");?></th>
								<th class="tdheader"><?php echo  $tr->translate("NOTE");?></th>
								<th class="tdheader"><?php echo  $tr->translate("BY_USER");?></th>
								<th class="tdheader"><?php echo  $tr->translate("STATUS");?></th>
								<th class="tdheader"><?php echo  $tr->translate("ACTION");?></th>
							</tr>
						</thead>
						<tbody>
							<?php 
							$id = "table";
							$stringPagination = '<script type="text/javascript">
										$(document).ready(function(){
											$("#'.$id.'").tablesorter();
											$("#'.$id.'").tablesorter().tablesorterPager({container: $("#pagination_'.$id.'"),size:15});
											$("#pagedisplay").focus(function(){ this.blur(); 
										   });
										});
								</script>
								<div id="pagination_'.$id.'" class="pager" >
											<form >
												<table  style="width: 200px;"><tr>
												<td><img src="'.BASE_URL.'/images/first.gif" class="first"/></td>
												<td><img src="'.BASE_URL.'/images/previous.gif" class="prev"/></td>
												<td><input type="text" class="pagedisplay"/></td>
												<td><img src="'.BASE_URL.'/images/next.gif" class="next"/></td>
												<td><img src="'.BASE_URL.'/images/last.gif" class="last"/></td>
												<td><select class="pagesize" >
													<option selected="selected"  value="10">10</option>
													<option value="20">20</option>
													<option value="30">30</option>
													<option value="40">40</option>
													<option value="50">50</option>
													<option value="60">60</option>
													<option value="70">70</option>
													<option value="80">80</option>
													<option value="90">90</option>
													<option value="100">100</option>
													</select>
												</td>
												</tr>
												</table>
											</form>
									</div>	';
							$footer="";
							if(!empty($this->rs)){
								foreach ($this->rs as $key=>$rs){
									$edit_status = '';
									if($rs["is_approve"]==1){ //$rs["pedding_stat"]>3
										$edit_status = "style='pointer-events: none;cursor: default;color: #ccc;'";
									}
							?>
								<tr class="normal">
									<td class="items-no"><?php echo $key+1;?></td>
									<td class="items"><?php echo $rs["transfer_no"];?></td>
									<td class="items"><?php echo date('d-M-Y',strtotime($rs["transfer_date"]));?></td>
									<td class="items"><?php echo $rs["location_name"];?></td>
									<td class="items"><?php echo $rs["to_location_name"];?></td>
									<td class="items"><?php echo $rs["total_qty"];?></td>
									<td class="items"><?php echo $rs["note"];?></td>
									<td class="items"><?php echo $rs["user_id"];?></td>
									<td class="items"><?php echo $rs["status"];?></td>
									<td class="items-no" style="white-space: nowrap;">
										<a <?php echo $edit_status;?> href="<?php echo $this->baseUrl();?>/product/mrcheck/approve/id/<?php echo $rs["id"]?>"><?php echo  $tr->translate("CHECK");?></a> | 
										<a target="_blank" href="<?php echo $this->baseUrl();?>/report/product/rpt-transfer-productdetail/id/<?php echo $rs["id"]?>"><?php echo  $tr->translate("PRINT");?></a>
									</td>
								</tr>
							<?php $counter='<strong style="float:right;padding:5px">Number of record(s): '.count($this->rs).'</strong>'; 
								$footer = '<div class="footer_list">'.$stringPagination.$counter.'</div>';
							}}?>
						</tbody>
					</table></div></form><?php echo $footer?>
						<?php //echo $this->list; ?>
			    </div>
		   </div>
		</div>
	</div>
</div>
<script>
$( document ).ready(function() {
   // $("#plan").val('<?php echo $this->search['plan']?>');
    //$("#branch").val('<?php echo $this->search['branch']?>');
});
</script>