<?php 
$tr=Application_Form_FrmLanguages::getCurrentlanguage();
$brach_name =  $this->branch;
$formFilter = $this->formFilter;
?>
<title><?php echo $tr->translate("RPT_TRANSFER_PRODUCT");?></title>
<div class="row">
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-globe"></i><?php echo $tr->translate("RPT_TRANSFER_PRODUCT");?>
				</div>
				<div class="btn-group pull-right">
						 <?php 	echo $this->render('printbutton.phtml');?>
				</div>
			</div>
            <div class="portlet-body form frmfilter">
				 <form class="form-horizontal" method="post" action="" >
				<div class="form-body">
							<div class="form-group">
								<div class="col-md-3">
									<?php echo $formFilter->getElement('ad_search');?>
								</div>
								<div class="col-md-3">
									<?php echo $formFilter->getElement('branch');?>
								</div>
								<div class="col-md-3">
									<?php echo $formFilter->getElement('start_date');?>
								</div>
								<div class="col-md-3">
									<?php echo $formFilter->getElement('end_date');?>
								</div>
							</div>		
							<div class="form-group">
								<div class="col-md-3">
									<button class="btn btn-primary col-md-12" value="" ><i class="fa fa-save"></i>&nbsp;<?php echo $tr->translate("REFRESH");?></button>
								</div>
							</div>		
					</div>
				</form>
	<div style="min-height:26cm; margin:0 auto; padding:0.2cm 0.2cm 0cm 0.2cm">	
	<div id="divPrint" style="width: 100%;">
	<style>
		.style{
			line-height: 25px;font-size: 12px !important;
			font-family: 'Khmer OS Battambang';
		}
		ul{margin: 0;padding:0;}
		table tr td ul li{text-align: center;list-style: none;line-height: 25px; font-weight: bold;}
		th{padding: 5px;}
		.hover:hover{background: #ccc;}
		td.table2excel tbody tr td span {
		    display: block;
		    padding: 0;
		    width: 100%;
		}
	</style>
		<table style="font-family: 'Khmer OS Content'; width:100%;">
			<tbody>
			<tr>
		    	<td align="center">
		        	<table width="100%" style="font-family: 'Khmer OS Battambang';" cellpadding="0" cellpadding="0">
		            	<tbody><tr>
		                	<td width="20%" valign="top"><img src="<?php echo $this->baseUrl();?>/images/logo.jpg" height="55px"></td>
		                	<td width="60%" valign="top">
		                		<ul>
		                			<li style="text-align:center; font-size:16px; font-family:'Khmer MEF2'"><?php echo $tr->translate("COMPANY_CUSTOMER");?></li>
		                			<li style="text-align:center; font-size:14px; font-family:'Khmer MEF2'"><?php echo $tr->translate("RPT_TRANSFER_PRODUCT");?></li>
		                			<li style="text-align:center; font-size:14px;"><?php if (!empty($this->rssearch['start_date'])){ echo date("d/m/Y",strtotime($this->rssearch['start_date']));?> ដល់ <?php echo date("d/m/Y",strtotime($this->rssearch['end_date']));}?></li>
		                		</ul>
		                	</td>
		                    <td width="20%"></td>
		                </tr> 
		                <tr>
		                	<td colspan="3" valign="top">
		                		<table width="100%" cellpadding="0" cellspacing="0">
		                			<tbody><tr>
		                				<td style="font-size: 11px;">
		                				    <span style="white-space: nowrap;"><?php //echo $tr->translate("ADDRESS_COMPANY");?></span>
		                					<br><?php //echo $tr->translate("TEL_COMPANY");?> 
		                				</td>
		                				<td width="65%"></td>
		                			</tr>
				                </tbody></table>
				              </td>
				           </tr>   
		            </tbody></table>
		        </td>
		    </tr>
		    <tr>
		    	<td class="table2excel" id="exportExcel">
		            <table border="1" style="border-collapse:collapse;border:1px solid #000; font-size:12px;" width="100%" cellspacing="0">
		                 <thead>
		                 <tr bgcolor="#c1d0f3" class="style" align="center" style="font-weight:bold;line-height: 30px; font-size:12px; padding:1px 0px; white-space: nowrap; ">
		                    <td >&nbsp;<?php echo $tr->translate("NUM");?>&nbsp;</td>
							<td >&nbsp;<?php echo  $tr->translate("TRANSFER_NO");?>&nbsp;</ts>
							<td >&nbsp;<?php echo $tr->translate("TRANSFER_DTE");?>&nbsp;</td>
							<td>&nbsp;<?php echo $tr->translate("FROM_LOCATION");?>&nbsp;</td>
							<td>&nbsp;<?php echo $tr->translate("TO_LOCATION");?>&nbsp;</td>
							<td>&nbsp;<?php echo $tr->translate("TOTAL_QTY");?>&nbsp;</td>
							<td>&nbsp;<?php echo $tr->translate("NOTE");?>&nbsp;</td>
							<td>&nbsp;<?php echo $tr->translate("APPROVE");?>&nbsp;</td>
							<td>&nbsp;<?php echo $tr->translate("ACTION");?>&nbsp;</td>
							<td>&nbsp;<?php echo $tr->translate("BY_USER");?>&nbsp;</td>
							<td>&nbsp;<?php echo $tr->translate("STATUS");?>&nbsp;</td>
		                </tr>
		                </thead>
		                <tbody>
		                <?php $num=1; 
		                $r_netotal = 0;$r_paid = 0; $r_balance = 0;
		                $d_netotal = 0;$d_paid = 0; $d_balance = 0;
		                $b_netotal = 0;$b_paid = 0; $b_balance = 0;
		                if(!empty($this->rs))foreach ($this->rs AS $index => $rs){?>
						<tr class='row-format<?php echo $num; $num=1-$num;?> hover' style="border:1px solid #000;">
						   <td align="center" style="white-space: nowrap;">&nbsp;<?php echo $index+1?>&nbsp;</td>
						   
						   <td style="white-space: nowrap;"><a style="color:#000;text-decoration: none;" target="_blank" href="<?php echo $this->baseUrl()."/report/product/rpt-transfer-productdetail/id/".$rs["id"];?>">&nbsp;<?php echo $rs["transfer_no"];?></a>&nbsp;</td>
						   <td style="white-space: nowrap;"><a style="color:#000;text-decoration: none;" target="_blank" href="<?php echo $this->baseUrl()."/report/product/rpt-transfer-productdetail/id/".$rs["id"];?>">&nbsp;<?php echo date("d-M-Y",strtotime($rs["transfer_date"]));?></a>&nbsp;</td>
						   <td style="white-space: nowrap;"><a style="color:#000;text-decoration: none;" target="_blank" href="<?php echo $this->baseUrl()."/report/product/rpt-transfer-productdetail/id/".$rs["id"];?>">&nbsp;<?php echo $rs["location_name"];?></a>&nbsp;</td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["to_location_name"];?>&nbsp;</td>
						   <td align="center" style="white-space: nowrap;">&nbsp;<?php echo $rs["total_qty"];?>&nbsp;</td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["note"];?>&nbsp;</td>
						   <td align="center" style="white-space: nowrap;"><?php echo $rs["approve"];?></td>
						   <td align="center" style="white-space: nowrap;"><?php echo $rs["receive"];?></td>
						   <td align="center"  style="white-space: nowrap;">&nbsp;<?php echo $rs["user_id"];?>&nbsp;</td>
						   <td align="center"  style="white-space: nowrap;">&nbsp;<?php echo $rs["status"];?>&nbsp;</td>
						</tr>
						
                  <?php   }?> 
                 </tbody>
		           </table>
		            <br>
		             
		              <br>
		              <table align="center" width="100%">
						   <tbody><tr style="font-size: 11px;">
						        <th style="width:20%;text-align:center;  font-family:'Khmer MEF2'">យល់ព្រមដោយ</th>
						        <th></th>
						        <th style="width:20%;text-align:center; font-family:'Khmer MEF2'">ត្រួតពិនិត្យដោយ</th>
						        <th></th>
						        <th style="width:20%;text-align:center;font-family:'Khmer MEF2'">រៀបចំដោយ</th>
						   </tr>
						</tbody>
					</table>	
		    		</td>
		    	</tr>
			</tbody>
		</table>
		</div>
	  </div>		
	</div>
	 </div>
   </div>
</div>
<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>
<?php 
	echo $this->render('printscript.phtml');
?>
