<?php 
$tr=Application_Form_FrmLanguages::getCurrentlanguage();
 
?>
<title><?php echo $tr->translate("RPT_TRANSFER_PRODUCT_DETAIL");?></title>
<div class="row">
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-globe"></i><?php echo $tr->translate("RPT_TRANSFER_PRODUCT_DETAIL");?>
				</div>
						<div class="btn-group pull-right">
							 <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-delay="1000" data-close-others="true" aria-expanded="false">
							   Actions <i class="fa fa-angle-down"></i>
							 </button>
								<ul class="dropdown-menu" role="menu">
									<li>
										<a href="#" onclick="doPrint();">
											<i class="fa fa-print" aria-hidden="true"></i>&nbsp;&nbsp;Print
										</a>
									</li>
									<li>
										<a href="#" onClick="exports()"><i class="fa fa-file-excel-o" aria-hidden="true"></i>&nbsp;&nbsp;Export Excel </a>
									</li>
									
								</ul>
					</div>
			</div>
            <div class="portlet-body form frmfilter">
					<div style="clear:both;"></div>	
	<div style=" min-height:28cm; margin:0 auto; border: 1px dotted #ccc; padding:0px 0.2cm">
	<div id="divPrint" style="width: 100%;">
	<style>
		.style{
			line-height: 20px;font-size: 12px !important;
			font-family: 'Khmer OS Battambang';
		}
		ul{margin: 0;padding:0;}
		table tr td ul li{text-align: center;list-style: none;line-height: 25px; font-weight: bold;}
		th{padding: 5px;}
		ul.pur_info li{line-height:18px; 
				font-weight: normal !important;}
		ul.pur_info li strong{font-weight: bold;}
       .hover:hover{background: #ccc;}
	</style>
		<table style="font-family: 'Khmer OS Content'; width:100%;">
			<tbody>
			<tr>
		    	<td align="center">
		        	<table width="100%" style="font-family: 'Khmer OS Battambang';" cellpadding="0" cellpadding="0">
		            	<tbody><tr>
		                	<td width="20%" valign="top"><img src="<?php echo $this->baseUrl();?>/images/logo.jpg" height="55px"></td>
		                	<td width="60%" valign="top">
		                		<ul>
		                			<li style="text-align:center; font-size:13px; font-family:'Khmer OS Muol Light'"><?php echo $tr->translate("COMPANY_CUSTOMER");?></li>
		                			<li style="text-align:center; font-size:13px; font-family:'Khmer OS Muol Light'"><?php echo $tr->translate("RPT_REQUEST_PRODUCT_DETAIL");?></li>
		                		</ul>
		                	</td>
		                    <td width="20%"></td>
		                </tr> 
		                <tr>
		                	<td colspan="3" valign="top">
		                		
				                <table width="100%" cellpadding="0" cellspacing="0" >
		                			<tbody>
		                			<tr>
		                				<td style="font-size: 12px;" valign="top">
		                				   <ul class='pur_info'>
			                					<li style="text-align: left;"><strong><?php echo $tr->translate("REQUEST_NAME");?> : </strong><?php echo $this->row['staff_name'];?></li>
			                					<li style="text-align: left;"><strong><?php echo $tr->translate("STAFF_REQ_NO");?> : </strong><?php echo $this->row['staff_no'];?></li>
			                					<li style="text-align: left;"><strong><?php echo $tr->translate("POSTION");?> : </strong><?php echo $this->row['staff_position'];?></li>
			                					<li style="text-align: left;"><strong><?php echo $tr->translate("NONTE");?> : </strong><?php echo $this->row['note'];?></li>
		                					</ul>
		                				</td>
		                				<td width="50%"></td>
		                				<td style="font-size: 12px;" valign="top">
		                				   <ul class='pur_info'>
			                					<li style="text-align: left;"><strong><?php echo $tr->translate("LOCATION");?> : </strong><?php echo $this->row['location_name'];?></li>
			                					<li style="text-align: left;"><strong><?php echo $tr->translate("REQUEST_NO");?> : </strong><?php echo $this->row['reques_no'];?></li>
			                					<li style="text-align: left;"><strong><?php echo $tr->translate("REQUEST_DATE");?> : </strong><?php echo date("d-M-Y",strtotime($this->row['date_request']));?></li>
		                					</ul>
		                				</td>
		                			</tr>
				                 </tbody>
				                </table>
				              </td>
				           </tr>   
		            	</tbody>
		            </table>
		        </td>
		    </tr>
		    <tr>
		    	<td class="table2excel" id="exportExcel"> 
		            <table border="1" style="border-collapse:collapse;border:1px solid #000; font-size:12px;" width="100%" cellspacing="0">
		                 <tbody>
		                 <tr bgcolor="#ccc" class="style" align="center" style="font-weight:bold; line-height: 20px; font-size:14px; padding:1px 0px; white-space: nowrap; ">
		                    <td>&nbsp;<?php echo $tr->translate("NUM");?></td>
		                    <td>&nbsp;<?php echo $tr->translate("ITEM_CODE");?></td>
							<td><?php echo $tr->translate("PRODUCT_NAME");?></td>
							<td>&nbsp;<?php echo $tr->translate("REQUEST_QTY");?></td>
							<td>&nbsp;<?php echo $tr->translate("RECEIVE_QYT");?></td>
							<td width="10%">&nbsp;<?php echo $tr->translate("COST");?></td>
							<td width="10%"><?php echo $tr->translate("TOTAL");?></td>
							<td><?php echo $tr->translate("NOTE");?></td>
		                </tr>
		                <?php $num=1; 
		               
		                if(!empty($this->rs))foreach ($this->rs AS $index => $rs){?>
		                 <?php 
						    
						 ?>
						<tr class='row-format<?php echo $num; $num=1-$num;?> hover' style="border:1px solid #000;">
						   <td align="center" style="white-space: nowrap;">&nbsp;<?php echo $index+1?></td>
						   <td style="white-space: nowrap;">&nbsp;<?php  echo $rs["item_code"];?></td>
						   <td style="white-space: nowrap;">&nbsp;<?php  echo $rs["item_name"];?></td>
						   <td style="white-space: nowrap; text-align:center;">&nbsp;<?php echo $rs["request_qty"]."&nbsp;".$rs['measure'];?></td>
						   <td style="white-space: nowrap; text-align:center;">&nbsp;<?php echo $rs["receive_qty"]."&nbsp;".$rs['measure'];?></td>
						   <td style="white-space: nowrap; min-width: 120px;">&nbsp;$&nbsp;<?php  echo number_format($rs["cost"],2);?></td>
						   <td style="white-space: nowrap; min-width: 120px;">&nbsp;$&nbsp;<?php echo  number_format($rs["receive_qty"]*$rs["cost"],2);?></td>
						   <td style="white-space: nowrap; min-width: 120px;">&nbsp;<?php echo $rs["note"]; ?></td>
						</tr>
						   <?php 
                    }?>
					 
		                </tbody>
		           </table>
		              <br>
		              <table align="center" width="100%">
						   <tbody><tr style="font-size: 11px;">
						        <th style="width:20%;text-align:center;  font-family:'Khmer MEF2'">យល់ព្រមដោយ</th>
						        <th></th>
						        <th style="width:20%;text-align:center; font-family:'Khmer MEF2'">ត្រួតពិនិត្យដោយ</th>
						        <th></th>
						        <th style="width:20%;text-align:center;font-family:'Khmer MEF2'">រៀបចំដោយ</th>
						   </tr>
						</tbody>
					</table>	
		    		</td>
		    	</tr>
			</tbody>
		</table>
		</div>
	  </div>		
	</div>
	 </div>
   </div>
</div>
<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>
<script>
function doPrint() {var divToPrint = document.getElementById('divPrint');var htmlToPrint = '' +'<style type="text/css">' +'</style>';htmlToPrint += divToPrint.outerHTML;window.document.write(htmlToPrint);window.print();window.close();}
</script>
