<?php 
$tr=Application_Form_FrmLanguages::getCurrentlanguage();
$brach_name =  $this->branch;
$formFilter = $this->formFilter;
//print_r($this->product);exit();
?>
<title><?php echo $tr->translate("Adjust Stock Report");?></title>
<div class="row">
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-globe"></i><?php echo $tr->translate("Adjust Stock Report");?>
				</div>
				<div class="btn-group pull-right">
					<?php 	echo $this->render('printbutton.phtml');?>
				</div>
			</div>
            <div class="portlet-body form frmfilter">
				<form method="post" action=" ">
					<div class="form-body">
							<div class="form-group">
								<label class="control-label col-md-3">
									<?php echo $formFilter->getElement('ad_search');?>
								</label>
								<label class="control-label col-md-3">
									<?php echo $formFilter->getElement('branch');?>
								</label>
								<label class="control-label col-md-3">
									<?php echo $formFilter->getElement('brand');?>
								</label>
								<label class="control-label col-md-3">
									<?php echo $formFilter->getElement('category');?>
								</label>
								
							</div>
							<div class="form-group">
								<label class="control-label col-md-3">
									<?php echo $formFilter->getElement('model');?>
								</label>
								<label class="control-label col-md-3">
									<?php echo $formFilter->getElement('size');?>
								</label>
								<label class="control-label col-md-3">
									<?php echo $formFilter->getElement('color');?>
								</label>
								<label class="control-label col-md-3">
									<?php echo $formFilter->getElement('status_qty');?>
								</label>
							</div>	
							<div class="form-group">
								<label class="control-label col-md-9">
									<?php //echo $formFilter->getElement('model');?>
								</label>
								<label class="control-label col-md-3">
									<button type="submit" class="btn btn-primary col-md-12"><?php echo $tr->translate("SEARCH");?></button>
								</label>
							</div>
							
						
				</div><div style="clear:both;"></div>	
				</form>
	<div style="min-height:26cm; margin:0 auto; padding:0.2cm 0.2cm 0cm 0.2cm">	
	<div id="divPrint" style="width: 100%;">
	<style>
		.style{
			line-height: 20px;font-size: 9px !important;
			font-family: 'Khmer OS Battambang';
		}
		ul{margin: 0;padding:0;}
		table tr td ul li{text-align: center;list-style: none;line-height: 25px; font-weight: bold;}
		th{padding: 5px;}
		.hover:hover{background: #ccc;}
	</style>
		<table style="font-family: 'Khmer OS Content'; width:100%;">
			<tbody>
			<tr>
		    	<td align="center">
		        	<table width="100%" style="font-family: 'Khmer OS Battambang';" cellpadding="0" cellpadding="0">
		            	<tbody><tr>
		                	<td width="25%" valign="top"><img src="<?php echo $this->baseUrl();?>/images/logo.jpg" height="85px"></td>
		                	<td width="50%" valign="top">
		                		<ul>
		                			<li style="text-align:center; font-size:16px; font-family:'Khmer MEF2'"><?php echo $tr->translate("COMPANY_CUSTOMER");?></li>
		                			<li style="text-align:center; font-size:13px; font-family:'Khmer MEF2'"><?php echo $tr->translate("RPT_ADJUST_STOCK");?></li>
		                			<!-- <li style="text-align:center; font-size:13px;"><?php //echo date("d/m/Y",strtotime($this->rssearch['start_date']));?> ដល់ <?php //echo date("d/m/Y",strtotime($this->rssearch['end_date']));?></li> -->
		                		</ul>
		                	</td>
		                    <td width="25%"></td>
		                </tr> 
		                <tr>
		                	<td colspan="3" valign="top">
		                		<table width="100%" cellpadding="0" cellspacing="0">
		                			<tbody><tr>
		                				<td style="font-size: 11px;">
		                				    <span style="white-space: nowrap;"><?php //echo $tr->translate("ADDRESS_COMPANY");?></span>
		                					<br><?php //echo $tr->translate("TEL_COMPANY");?> 
		                				</td>
		                				<td width="65%"></td>
		                			</tr>
				                </tbody></table>
				              </td>
				           </tr>   
		            </tbody></table>
		        </td>
		    </tr>
		    <tr>
		    	<td id="exportExcel">
		    		<table class="table2excel" border="1"​ style="border-collapse:collapse;border:1px solid #000; font-size:12px;" width="100%" cellspacing="0">
		                 <thead>
		                 	<tr bgcolor="#c1d0f3" class="style" align="center" style="font-weight:bold;line-height: 30px; font-size:12px; padding:1px 0px; white-space: nowrap; ">
			                    <td>&nbsp;<?php echo $tr->translate("NUM");?>&nbsp;</td>
								<td>&nbsp;<?php echo $tr->translate("ITEM_CODE");?>&nbsp;</ts>
								<td>&nbsp;<?php echo $tr->translate("ITEM_NAME");?>&nbsp;</td>
								<td>&nbsp;<?php echo $tr->translate("BARCODE");?>&nbsp;</td>
								<td>&nbsp;<?php echo $tr->translate("MEASURE");?>&nbsp;</td>
								<td>&nbsp;<?php echo $tr->translate("QTY_BEFORE");?>&nbsp;</td>
								<td>&nbsp;<?php echo $tr->translate("NEW_QTY");?>&nbsp;</td>
								<td>&nbsp;<?php echo $tr->translate("DIFFER_QTY");?>&nbsp;</td>
								<td>&nbsp;<?php echo $tr->translate("ADJUST_BY");?>&nbsp;</td>
								<td>&nbsp;<?php echo $tr->translate("DATE");?>&nbsp;</td>
			                </tr>
		                </thead>
		                <tbody>
		                <?php $num=1; 
		                $r_netotal = 0;$r_paid = 0; $r_balance = 0;
		                $d_netotal = 0;$d_paid = 0; $d_balance = 0;
		                $b_netotal = 0;$b_paid = 0; $b_balance = 0;
		                if(!empty($this->product))foreach ($this->product AS $index => $row){?>
						<tr class='row-format<?php echo $num++; ?>' id="item_<?php echo $index; ?>">
								<td align="center">&nbsp;<?php echo $index+1 ?>&nbsp;</td>
								<td>&nbsp;<?php echo $row["item_code"]?>&nbsp;</td>
								<td>&nbsp;<?php echo $row["item_name"]."<br />&nbsp;(".$row["cat"]." ".$row["brand"]." ".$row["model"]." ".$row["size"]." ".$row["color"].")"?>&nbsp;</td>
								<td>&nbsp;<?php echo $row["barcode"]?>&nbsp;</td>
								<td >&nbsp;<?php echo $row["measure"]?>&nbsp;</td>
								<td align="center">&nbsp;<?php echo $row["cur_qty"]?>&nbsp;</td>
								<td align="center">&nbsp;<?php echo $row["qty_adjust"]?>&nbsp;</td>
								<td align="center">&nbsp;<?php echo $row["defer_qty"]?>&nbsp;</td>
								<td align="center">&nbsp;<?php echo $row["username"]?>&nbsp;</td>
								<td align="center">&nbsp;<?php echo date("d-M-Y",strtotime($row["date"]));?>&nbsp;</td>
								<!-- <td class="center">
									<?php //if($row["status"] == 1){?>
									<span class="label label-sm label-success"><?php //echo $tr->translate("ACTIVE");?> </span>
									<?php //}else{?>
									<span class="label label-sm label-danger"><?php //echo $tr->translate("DEACTIVE");?> </span>
									<?php //}?>
								</td> -->
							</tr>
						  <?php }?> 
		                </tbody>
		           </table>
		            <br>
		              <br>
		              <table align="center" width="100%">
						   <tbody><tr style="font-size: 11px;">
						        <th style="width:20%;text-align:center;  font-family:'Khmer MEF2'">យល់ព្រមដោយ</th>
						        <th></th>
						        <th style="width:20%;text-align:center; font-family:'Khmer MEF2'">ត្រួតពិនិត្យដោយ</th>
						        <th></th>
						        <th style="width:20%;text-align:center;font-family:'Khmer MEF2'">រៀបចំដោយ</th>
						   </tr>
						</tbody>
					</table>	
		    		</td>
		    	</tr>
			</tbody>
		</table>
		</div>
	  </div>		
	</div>
	 </div>
   </div>
</div>
<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>
<?php 
	echo $this->render('printscript.phtml');
?>
<script>
/*var currentTime = new Date();
var month = currentTime.getMonth() + 1;
var day = currentTime.getDate();
var year = currentTime.getFullYear();
	var date =(year + "-" + month + "-" + day );

var start_date = $('#start_date').val();
var end_date =$('#end_date').val();

if(end_date!="" | start_date!=""){
    start_date = $('#start_date').val();
	end_date =$('#end_date').val();
	
}else{
	start_date = $('#start_date').val(date);
	end_date = $('#end_date').val(date);
}*/

<?php //$url_item_filter =  $this->url(array('module'=>'report','controller'=>'index','action'=>'get-item-filter')); ?>
/*function getProductFilter(){
	var location_id=$("#LocationId").val();
	var branch_id = $('#branch_id').val();
	var category_id = $('#category_id').val();
		$.ajax({
			url:"<?php //echo $url_item_filter;?>",
			type:"post",
			data:{'category_id':category_id,'branch_id':branch_id,'location_id':location_id},
			success: function(data){
				items = $.parseJSON(data);
				if(items){
					 $('#item').empty();
					 $('#item').val('').trigger("liszt:updated");
					 $('#item').append($("<option></option>").attr("value","").text("Please Select Item"));
					 for (var index = 1 ; index <= items.length; index++) {
							$('#item').append($("<option></option>").attr("value",items[index-1]['pro_id']).text(items[index-1]['item_code'] + items[index-1]['item_name'])); 
							$("select#item").find("option#items[index-1]['pro_id']").attr("selected", true);
					 }           
					$('#item').val('').trigger("liszt:updated");
				}else{
					 $('#item').empty();
					 $('#item').val('').trigger("liszt:updated");
						 $('#item').append($("<option></option>").attr("value","").text("No Items Result!"));
						 $('#item').val('').trigger("liszt:updated");
				}
			},
			error:function(){
			}
		});
	}*/
</script>
