<?php 
$tr=Application_Form_FrmLanguages::getCurrentlanguage();
$brach_name =  $this->branch;
$result = $this->stockin;
$db = new report_Model_DbProduct();
//print_r($result);
?>
<?php $formFilter = $this->formFilter; ?>
<title><?php echo $tr->translate("STOCK_SUMMARY");?></title>
<div class="row">
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-globe"></i><?php echo $tr->translate("STOCK_SUMMARY");?>
				</div>
				<div class="btn-group pull-right">
					<?php 	echo $this->render('printbutton.phtml');?>
				</div>
			</div>
            <div class="portlet-body form frmfilter">
				<form method="post" action="">
					<div class="form-body">
							<div class="form-group">
								<label class="control-label col-md-3">
									<?php echo $formFilter->getElement('ad_search');?>
								</label>
								<label class="control-label col-md-3">
									<?php echo $formFilter->getElement('branch');?>
								</label>
								<label class="control-label col-md-3">
									<?php echo $formFilter->getElement('suppliyer_id');?>
								</label>
								<label class="control-label col-md-3">
									<?php echo $formFilter->getElement('measure');?>
								</label>
							</div>
							<div class="form-group">
								<label class="control-label col-md-3">
									<?php echo $formFilter->getElement('start_date');?>
								</label>
								<label class="control-label col-md-3">
									<?php echo $formFilter->getElement('end_date');?>
								</label>
							</div>
							<div class="form-group">
								<label class="control-label col-md-2  ">
									<button type="submit" class="btn btn-primary col-md-12"><?php echo $tr->translate("SEARCH");?></button>
								</label>
							</div>
							
						
				</div><div style="clear:both;"></div>	
				</form> 
	<div style="min-height:26cm; margin:0 auto; padding:0.2cm 0.2cm 0cm 0.2cm">	
	<div id="divPrint" style="width: 100%;">
		<style>
			.style{
					line-height: 20px;font-size: 12px !important;
					font-family: 'Khmer OS Battambang';
				}
				ul{margin: 0;padding:0;}
				table tr td ul li{text-align: center;list-style: none;line-height: 25px; }
				th{padding: 0px;}
				table thead tr th{
					line-height:30px;
					background:#ccc;
					font-size:15px;
					padding:3px;
				}
				table tr td{
					font-size:12px;
				}
				ul.pur_info li{line-height:18px; 
						font-weight: normal !important;}
				ul.pur_info li strong{font-weight: bold;}
			   .hover:hover{background: #ccc;}
				table.collape td{border: 1px solid #000 !important;}
				table { page-break-inside:auto }
				tr{ page-break-inside:avoid; page-break-after:auto; }
				#header {
				  display: table-header-group;
				  page-break-inside:avoid; page-break-after:auto;
				}
		
		</style>
		<table style="font-family: 'Khmer OS Content'; width:99%;">
			<tbody>
			<tr>
		    	<td align="center">
		        	<table width="100%" style="font-family: 'Khmer OS Battambang';" cellpadding="0" cellpadding="0">
		            	<tbody><tr>
		                	<td width="25%" valign="top"><img src="<?php echo $this->baseUrl();?>/images/logo.jpg" height="85px"></td>
		                	<td width="50%" valign="top">
								<ul>
								    <li style="text-align:center; font-size:18px; font-family:'Khmer MEF2'"><?php echo $tr->translate("COMPANY_CUSTOMER");?></li>
		                			<li style="text-align:center; font-size:14px; font-family:'Khmer MEF2'"><?php echo $tr->translate("STOCK_SUMMARY");?></li>
									<li style="text-align:center; font-size:14px; font-family:'Khmer MEF2'"><?php if($this->search!=""){echo $this->searchs;}else{echo "All Branch";}?></li>
		                			<!--<li style="text-align:center; font-size:13px;"><?php //echo date("d/m/Y",strtotime($this->rssearch['start_date']));?> ដល់ <?php echo date("d/m/Y",strtotime($this->rssearch['end_date']));?></li>-->
		                		</ul>
		                	</td>
		                    <td width="25%"></td>
		                </tr> 
		                <tr>
		                	<td colspan="3" valign="top">
		                		<table width="100%" cellpadding="0" cellspacing="0">
		                			<tbody><tr>
		                				<td style="font-size: 11px;">
		                				    <span style="white-space: nowrap;"><?php //echo $tr->translate("ADDRESS_COMPANY");?></span>
		                					<br><?php //echo $tr->translate("TEL_COMPANY");?> 
		                				</td>
		                				<td width="65%"></td>
		                			</tr>
				                </tbody></table>
				              </td>
				           </tr>   
						</tbody>
					</table>
		        </td>
		    </tr>
		    <tr>
		    	<td class="table2excel" >
		    		<table border="1"​ style="border-collapse:collapse;border:1px solid #000; font-size:12px;" width="100%" cellspacing="0">
		                 <tbody>
						  <?php $num=1; 
			               $total_pur_qty = 0;
						   $total_begin_qty =0;
						   $toal_issus_qty =0;
						   $total_edning_qty = 0;
						   $total_price =0;
						   $total_amount = 0;
						  ?>
						<thead>
							<tr bgcolor="#c1d0f3" class="style" align="center" style="font-weight:bold;line-height: 30px; font-size:12px; padding:1px 0px; white-space: nowrap; ">
			                    <td>&nbsp;<?php echo $tr->translate("NUM");?>&nbsp;</td>
								<td>&nbsp;<?php echo $tr->translate("DATE_IN");?>&nbsp;</td>
								<td>&nbsp;<?php echo $tr->translate("VENDOR_NAME");?>&nbsp;</td>
								<td>&nbsp;<?php echo $tr->translate("ITEM_NAME");?>&nbsp;</td>
								<td>&nbsp;<?php echo $tr->translate("ITEM_CODE");?>&nbsp;</td>
								<td>&nbsp;<?php echo $tr->translate("ដើមគ្រា");?>&nbsp;</td>
								<td>&nbsp;<?php echo $tr->translate("ស្តុកចូល");?>&nbsp;</td>
								<!-- <td><?php //echo $tr->translate("សរុប");?></td> -->
								<td>&nbsp;<?php echo $tr->translate("ស្តុកចេញ");?>&nbsp;</td>
								<td>&nbsp;<?php echo $tr->translate("ស្តុកសល់");?>&nbsp;</td>
								<td>&nbsp;<?php echo $tr->translate("MEASURE");?>&nbsp;</td>
								<td>&nbsp;<?php echo $tr->translate("COST_PRICE");?>&nbsp;</td>
								<td>&nbsp;<?php echo $tr->translate("តម្លៃសរុប");?>&nbsp;</td>
								<td>&nbsp;<?php echo $tr->translate("OTHER");?>&nbsp;</td>
			                </tr>
		                </thead>
		                <?php 
		                if(!empty($this->stockin))foreach ($this->stockin AS $index => $rs){
		                        $rs_re = $db->getReceiveByPro($rs["id"],$this->search);
								$rs_deli = $db->getDeliByPro($rs["id"],$this->search);
								$pur_qty = $rs_re["qty_receive"];
								$issuse_qty = $rs_deli["deli_qty"];
								$begin_qty = ($rs["qty"]+$rs_deli["deli_qty"])-$rs_re["qty_receive"];
// 								$total_price = $total_price+$rs["price"];
						?>
						<tr class='tdborder row-format<?php echo $num; $num=1-$num;?> hover' style="border:1px solid #000;">
						   <td align="center" style="white-space: nowrap;">&nbsp;<?php echo $index+1;?>&nbsp;</td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo date("d-M-Y",strtotime($rs["date_in"]));?>&nbsp;</td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["vendor_name"];?>&nbsp;</td>
						   <td  >&nbsp;<?php echo $rs["item_name"];?></td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["item_code"];?>&nbsp;</td>
						  
						   <td align="center" style="white-space: nowrap;">&nbsp;<?php echo $begin_qty;?>&nbsp;</td>
						   <td align="center" style="white-space: nowrap;">&nbsp;<?php echo  $pur_qty;?>&nbsp;</td>
						    
						   <td align="center" style="white-space: nowrap;">&nbsp;<?php echo  $issuse_qty;?>&nbsp;</td>
						   <td align="center" style="white-space: nowrap;">&nbsp;<?php echo $rs["qty"];?>&nbsp;</td>
						   <td style="white-space: nowrap;">&nbsp;<?php echo $rs["measure"];?>&nbsp;</td>
						   <td align="right">&nbsp;$<span >&nbsp;&nbsp;<?php echo number_format($rs["price"],2);?></span>&nbsp;</td>
						   <td align="right">&nbsp;$<span >&nbsp;&nbsp;<?php echo number_format($rs["price"]*$rs["qty"],2);?></span>&nbsp;</td>
						   <td style="white-space: nowrap;">&nbsp;<?php //echo $rs["item_code"];?></td>
						</tr>
						<?php 
							 
						}?>
		                </tbody>
		           </table>
		            <br>
		              <table align="center" width="100%">
						   <tbody><tr style="font-size: 11px;">
						        <td style="width:20%;text-align:center;font-size:13px; font-family:'Khmer MEF2'">អនុម័តដោយ</td>
						        <td></td>
								<td style="width:20%;text-align:center;font-size:13px; font-family:'Khmer MEF2'">ត្រួតពិនិត្យដោយ</td>
								<td></td>
								<td style="width:20%;text-align:center;font-size:13px; font-family:'Khmer MEF2'">រៀបចំដោយ</td>
						   </tr>
						</tbody>
					</table>	
		         </td>  
		             
		    		 
		    	</tr>
			</tbody>
		</table>
		</div>
	  </div>		
	</div>
	 </div>
   </div>
</div>
<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>
<?php 
	echo $this->render('printscript.phtml');
?>
