<center>
<?php 
	$rs = $this->rs;
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
?>
<div id="PrintReceipt" style="border:1px dashed #ccc;width:28cm !important; padding: 0px; margin-bottom:30px; ">
			<style>
		.hearder_table{height:25px !important;}
		.defaulheight{line-height: 22px !important;}
		#PrintReceipt{display: table;}
		#pageFooter {
		    display: table-footer-group;
		}
#pageFooter:after {
    counter-increment: page;
    content:"Page " counter(page);
    left: 0; 
    top: 100%;
    white-space: nowrap; 
    z-index: 20px;
    -moz-border-radius: 5px; 
    -moz-box-shadow: 0px 0px 4px #222;  
    background-image: -moz-linear-gradient(top, #eeeeee, #cccccc);  
    background-image: -moz-linear-gradient(top, #eeeeee, #cccccc);  
  }
	</style>
		<table class="print" cellspacing="0" cellpadding="0" style="width:98%;font-family: 'Khmer OS Battambang' !important; font-size:12px !important; margin-top:0 auto;white-space:nowrap;">
			<tbody><tr height="40px;">
			    <td colspan="10" style="" align="center" valign="top">
					<table width="100%" style="font-size: 16px;margin-bottom: 0px;"   >
						<tr>
							<td width="30%" valign="top" align="center"></td>
							<td width="40%" align="center" valign="top" style="font-size: 16px;font-family:'Khmer MEF2';"><div >ព្រះរាជាណាចក្រកម្ពុជា</div>ជាតិ សាសនា ព្រះសាសនា
							</td>
							<td width="30%" valign="top"></td>
						</tr>
						<tr>
							<td valign="top" align="center"></td>
							<td align="center" valign="top" style=""><div style="font-size: 14px;font-family:'Khmer MEF2';">កិច្ចស​ន្យាទិញទំនិញ ចូល</div></td>
							<td valign="top"></td>
						</tr>
					</table>
			    </td>
			</tr>
			<style>
			.bold{
				font-weight:bold;
				}
			.tablesorter td{font-family:'khmer os battambang' !important;}
			.one{line-height: 15px;}
			table { page-break-inside:auto }
			  tr{ page-break-inside:avoid; page-break-after:auto; }
			#header {
			  display: table-header-group;
			  page-break-inside:avoid; page-break-after:auto;
			}
			#footer {
			  display: table-footer-group;
			}
			@page {
			       @bottom-left {
			            content: counter(page) "/" counter(pages);
			        }
			     }
			     table.collape td{font-size: 12px;}
			@media print {
			    footer {page-break-after: always;}
			}
			</style>			
			<tr height="80px">
				<td colspan="6" width="60%" valign="top">
					<table width="100%" style="font-size: 14px; !important">
						<tbody>
						<tr>
							<td width="100px;">&nbsp;ភាគីអ្នកផ្គត់ផ្គង់</td>
							<td width="1px"> :</td>
							<td style="padding-top:5px;">
								<label id="lbl_customer" class="one" style="font-size: 14px;"><?php echo $rs['customer_name']?></label>
							</td>
						</tr>
						<tr>
							<td>&nbsp;ទូរសព្ទ</td>
							<td colspan="1"> :</td>
							<td><label id="lbl_phone" class="one"><?php echo $rs['phone']?></label></td>
						</tr>
						
						<tr>
							<td width="100px;">&nbsp;ភាគីទិញ</td>
							<td width="1px"> :</td>
							<td style="padding-top:5px;">
								<label id="lbl_customer" class="one" style="font-size: 14px;"><?php echo $tr->translate("PARTY_SELL");?></label>
							</td>
						</tr>
						<tr>
							<td>&nbsp;ទូរសព្ទ</td>
							<td colspan="1"> :</td>
							<td><label id="lbl_phone" class="one"><?php echo $tr->translate('TEL_COMPANY')?></label></td>
						</tr>
					</tbody>
				</table>
				</td>
				<td colspan="4" valign="top">
				</td>
			</tr>
			<tr>
				<td colspan="10" valign="top">
					<table class="defaulheight" width="100%" border="0" style="font-family: Khmer OS Battambang , Times New Roman;font-size:12px;white-space:nowrap;margin-top:-5px;line-height: 13px;">
						<tbody><tr>
							<td colspan="6" valign="top">
								<div id="t_amountmoneytype">
									<table class="collape tablesorter" align="center" style=" width: 100%; padding: 0px; margin-top: 3px !important; border-collapse: collapse; border: 1px solid #000; font-size:15px;font-family:Khmer OS Battambang !important;  " id="table">
										<thead>
											<tr class="hearder_table" style="font-family:khmer os battambang;text-align:center;background:#f2f2f2 !important;font-weight:bold;"><td style="border:1px solid #000;font-size:12px;">លរ</td>
												<td style="border:1px solid #000;font-size:12px;"><strong style="color:#000;">ឈ្មោះមុខទំនិញ</strong></td>
												<td style="border:1px solid #000;font-size:12px;"><strong style="color:#000;">ឯកត្តា</strong></td>
												<td style="border:1px solid #000;font-size:12px;"><strong style="color:#000;">ខ្នាត</strong></td>
												<td style="border:1px solid #000;font-size:12px;"><strong style="color:#000;">បរិមាណសរុប</strong></td>
												<td style="border:1px solid #000;font-size:12px;"><strong style="color:#000;">តម្លៃរាយ</strong></td>
												<td style="border:1px solid #000;font-size:12px;"><strong style="color:#000;">សរុប</strong></td>
											</tr>
										</thead>
										<tbody>
										<?php 
										$index=0;
										if(!empty($this->rsdetail)){foreach($this->rsdetail as $key => $item){ $index++;?>
										<tr style="font-size:12px !important; text-align:center;font-weight:bold;">
											<td style="border:1px solid #000;"><?php echo $key+1;?></td>
											<td style="border:1px solid #000;text-align:left;min-width:230px;"><strong style="color:#000;">&nbsp;<?php echo $item['pro_name'];?> </strong></td>
											<td style="border:1px solid #000;"><strong style="color:#000;padding:0 3px;white-space: nowrap;"><?php echo $item['erkta'];?></strong></td>
											<td style="border:1px solid #000;"><strong style="color:#000;padding:0 3px;white-space: nowrap;"><?php echo $item['measue_name'];?></strong></td>
											<td style="border:1px solid #000;"><strong style="color:#000;padding:0 3px;white-space: nowrap;"><?php echo number_format($item['qty_order'],2);?></strong></td>
											<td style="border:1px solid #000;"><strong style="color:#000;padding:0 3px;white-space: nowrap;"><?php echo $item['price'];?></strong></td>
											<td style="border:1px solid #000;"><strong style="color:#000;padding:0 3px;white-space: nowrap;">$ <?php echo $item['sub_total'];?></strong></td>
										</tr>
										<?php } }?>
										<tr style=" font-size:12px !important;height:25px;;text-align:right;font-weight:bold;">
											<td style="border:1px solid #fff;border-right:1px solid #000" colspan="5"> <?php //echo number_format($rs['all_total_riel'],3)?>&nbsp;</td>
											<td style="border:1px solid #000;><strong style=" color:#000;">សរុប&nbsp;</td>
											<td style="border:1px solid #000;><strong style=" color:#000;">$ <?php //echo number_format($rs['net_total'],3)?> &nbsp;</td>
										</tr>
										<tr style=" font-size:12px !important;height:25px;;text-align:left;font-weight:bold;">
											<td style="border:1px solid #fff;font-size:13px !important;" colspan="7">- លក្ខខ័ណ្ឌធានា</td>
										</tr>
										<tr style=" font-size:12px !important;height:25px;font-weight:bold;">
											<td style="border:1px solid #fff;padding-left:15px;" colspan="7"><?php echo $rs['term_condition']?></td>
										</tr>
										<tr>
											<td  style="border:1px solid #fff; height: 24px;"></td>
											<td colspan="6" style="text-align:right;border:1px solid #fff; height: 24px;font-size:15px !important;">ថ្ងៃទី .............ខែ ...........ឆ្នាំ ...........</td>
											</tr>
										<tr style="font-size:15px !important;height:25px;font-weight:bold;">
											<td style="border:1px solid #fff;padding-left:15px;text-align: left;font-size:15px !important;font-family:'Khmer MEF2';" colspan="3"><?php echo $rs['customer_name']?></td>
											<td style="border:1px solid #fff;padding-left:15px;" colspan="1"></td>
											<td style="border:1px solid #fff;padding-left:15px;font-family:'Khmer MEF2';text-align: right;font-size:15px !important;" colspan="3"><?php echo $tr->translate("COMPANY_CUSTOMER");?></td>
										</tr>
										<tr>
											<td colspan="7" style="border:1px solid #fff; height: 25px;"></td>
										</tr>
										</tbody>
									</table>
								</div>
							</td>
						</tr>
					</tbody></table>
				</td>
			</tr>
		</tbody></table>
    </div>
    <div style="text-align: center;margin: 0 auto;"> 
    	<lable class="col-md-3" style=""></lable>
    	<div class="col-md-2">
			<a href="<?php echo $this->baseUrl();?>/sales/agreement"><button type="button" class="btn red btn-block btn-lg"><i class="fa fa-times"></i>ចាកចេញ</button></a>
		</div>
    	<lable class="col-md-2" style="">
             <button type="button" onclick="printinvoice();" name="btnsavenew" class="btn blue btn-block btn-lg"><i class="fa fa-print"></i> រក្សាទុក/បោះ ពុម្ភ </button>
		</lable>
		<lable class="col-md-3" style=""></lable>
	</div>
</center>
<script>
function printinvoice(){
	var printContents = document.getElementById('PrintReceipt').innerHTML;
    var originalContents = document.body.innerHTML;
    document.body.innerHTML = printContents;
    window.print();
    document.body.innerHTML = originalContents;
	document.getElementById("office_receipt").submit();
}
</script>
   