<?php $form=$this->form; 
	  $frm_agent = $this->form_user_detail;
?>
<style>
       td.quater-input select {
		    height: 32px;
		}
</style>
<style>
.image-box {
    text-align: center;
}
.image-box img {
    width: 150px;
    height: 140px;
    border: solid 1px #eee;
}
.button_browse {
    /*margin-top: 10px; */
    position: relative;
    overflow: hidden;
    text-align: center;
    width: 100%;
    height: 45px;
    cursor: pointer;
    background: #fbf9f9;
    border: 1px solid #e8e8e8;
}
.button_browse span {
    line-height: 40px;
    font-weight: 600;
    cursor: pointer;
}
input.btn_borwse_image {
    position: absolute;
    width: 100%;
    height: 45px;
    top: 0;
    left: 0;
    z-index: 2;
    opacity: 0;
    cursor: pointer;
}
.account-image {
    border: solid 1px #eee;
    width: 150px;
}
</style>
<script language="javascript">
      var temp=-1;
   
	function validateUser(field)
	{
		if(temp==1) return '* User name already exist!';
		else temp==-1;
	}
    function validatePassword(field)
	{
    	var com=$('#confirm_password').val();
    	var pwd=$('#password').val();
		if(com!=pwd) return '* Password mismatch!';		 
	}
</script>
<script type="text/javascript">
	$( document ).ready(function() {
		addRow();
		jQuery('#frm').validationEngine('attach', {promptPosition : "centerRight"});
		
	});
</script>
<?php 
	Application_Model_Decorator::removeAllDecorator($form);
	$cancel_url=$this->url(array(
		'module'=>'rsvAcl',
		'controller'=>'user',
		'action'=>'index',
	)); 	
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$url_cancel = $this->url(array('module'=>'rsvacl','controller'=>'user','action'=>'index'),null,true);
?>
<title><?php echo $tr->translate("ADD_USER")?></title>
<div class="row">
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-user" aria-hidden="true"></i> <?php echo $tr->translate("ADD_USER")?>
				</div>
				<div class="tools" >
					<a href="<?php echo $url_cancel;?>" class="btn btn-sm pull-right" style="color:white;">
					<i class="fa fa-undo"></i>	&nbsp;<?php echo $tr->translate("GO_BACK");?>
					</a>
				</div>
			</div>
			<div class="portlet-body form">
				<!-- BEGIN FORM-->
				<form id="frm" action="<?php //echo $url_submit; ?>" class="form-horizontal" enctype="multipart/form-data" method="post">
					<div class="card-box mt-10">
			    		 <ul class="nav  md-pills pills-primary nav-tab" role="tablist">
				            <li class="nav-item active">
				                <a class="nav-link " data-toggle="tab" href="#panel21" role="tab"><i class="fa fa-user ml-2"></i> <?php echo $tr->translate("USER_INFO");?></a>
				            </li>
				            <li class="nav-item">
				                <a class="nav-link" data-toggle="tab" href="#panel22" role="tab">
				                <i class="fa fa-users ml-2"></i> <?php echo $tr->translate("MENU_SALES_SALE_AGENT_ADD_SALE_AGENT_INFO");?>
				                </a>
				            </li>
				        </ul>
				    </div>
				    <div class="card-box mt-10">
				        <!-- Tab panels -->
				        <div class="tab-content vertical">
					        <!--Panel 1-->
					        <div class="tab-pane fade in active" id="panel21" role="tabpanel">
					        	<div class="col-md-6 col-sm-6 col-xs-12">
					        		<div class="form-group">
										<label class="control-label col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate('GENDER_TITLE');?><span class="required">
											</span>
										</label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<div class="input-icon right">
												<i class="fa"></i>
												<?php echo $form->getElement('title');?>
											</div>
										</div>
									</div>
									<div class="form-group">
										<label class="control-label col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate('FULL_NAME');?><span class="required">
											</span>
										</label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<div class="input-icon right">
												<i class="fa"></i>
												<?php echo $form->getElement('fullname');?>
											</div>
										</div>
									</div>
									<div class="form-group">
										<label class="control-label col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate('USER_NAME');?><span class="required">
										* </span>
										</label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<div class="input-icon right">
											<?php echo $form->getElement('username');?>
											</div>
										</div>
									</div>
									<div class="form-group">
										<label class="control-label col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate('EMAIL');?><span class="required">
											 </span>
										</label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<div class="input-icon right">
												<?php echo $form->getElement('email');?>
											</div>
										</div>
									</div>
									<div class="form-group">
										<label class="control-label col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate('PASSWORD');?><span class="required">
											 </span>
										</label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<div class="input-icon right">
												<?php echo $form->getElement('password');?>
											</div>
										</div>
									</div>
									<div class="form-group">
										<label class="control-label col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate('RE_PASSWORD');?><span class="required">
										* </span>
										</label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<div class="input-icon right">
												<?php echo $form->getElement('confirm_password');?></div>
										</div>
									</div>
					        	</div>
					        	<div class="col-md-6 col-sm-6 col-xs-12">
					        		<div class="form-group" >
										<label class="control-label col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate('USER_TYPE');?><span class="required">
											 </span>
										</label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<div class="input-icon right">
												<?php echo $form->getElement('user_type_id');?>
											</div>
										</div>
									</div>
									<div class="form-group" >
										<label class="control-label col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("STATUS");?>
										</label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<div class="input-icon right">
												<?php echo $form->getElement("status");?>
											</div>
										</div>
									</div>
									<div class="form-group">
										<label class="control-label col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("ASS_TO_LOCATION");?><span class="required">
											 </span>
										</label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<div class="input-icon right">
												<?php echo $form->getElement("LocationId");?>
											</div>
										</div>
									</div>
									
									<div class="form-group">
										<label class="control-label col-md-5 col-sm-5 col-xs-12">
										<input type="hidden" id="identity" name="identity" />
													<button class="btn btn-primary" type="button" id="new_item" onclick="addRow(1);" name="new_followup" value="New">
																	&nbsp;<img src="<?php echo $this->baseUrl()?>/images/icon/new-row.png" alt="">Add</button>
										</label>
											<label class="control-label col-md-7 col-sm-7 col-xs-12">
												<table class="collape" id="table_order" style="width: 100%;">
													<tr height="25px">
														<td class="sub-tdheader" width="20px"><?php echo $tr->translate("NUM");?></td>
														<td class="sub-tdheader"><?php echo $tr->translate("BRANCH_NAME");?></td>
													</tr>
												</table>
											</label>
											<label class="control-label col-md-5 col-sm-5 col-xs-12"><?php //echo $tr->translate("PHOTO");?>
												<span class="required">
												</span>
											</label>
											<div class="col-md-7 col-sm-7 col-xs-12">
												<br />
												<div class="input-icon right">
													<?php 
														$images = $this->baseUrl().'/images/profile.png';
														?>
														<input name="old_photo"  value="<?php echo $this->photo;?>" type="hidden" />
														<div class="account-image" >
															<div class="image-box">
																<img id="profile_wiew" src="<?php echo $images;?>" alt=""  />
															</div>
															<div class="button_browse">
															<div id='preview'></div>	
																	<span>Upload <span ><i class="fa fa-camera" aria-hidden="true"></i></span></span>
																	<input class="btn_borwse_image" type="file" id="signature" name="signature" />
															</div>
														</div>
													<?php //echo $frm_agent->getElement("signature");?>
												</div>
											</div>
										</div>
								
					        	</div>
					        	<div class="clearfix"></div>
					         </div>
					         <!--/.Panel 1-->
					          <!--Panel 2-->
					        <div class="tab-pane" id="panel22" role="tabpanel">
					        	<div class="col-md-6 col-sm-6 col-xs-12">
					        		<div class="form-group">
										<label class="control-label col-md-5 col-sm-5 col-xs-12">
										<?php echo $tr->translate("DEPARTMENT");?><span class="required">
											</span>
										</label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<div class="input-icon right">
												<i class="fa"></i>
												<?php echo $frm_agent->getElement("department");?>
											</div>
										</div>
									</div>
									<div class="form-group">
										<label class="control-label col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("AGENT_CODE");?><span class="required">
											</span>
										</label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<div class="input-icon right">
												<i class="fa"></i>
												<?php echo $frm_agent->getElement("code");?>
											</div>
										</div>
									</div>
									<div class="form-group">
										<label class="control-label col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("USER_NAME");?> <span class="required">
											</span>
										</label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<div class="input-icon right">
												<i class="fa"></i>
												<?php echo $frm_agent->getElement("name");?>
											</div>
										</div>
									</div>
									<div class="form-group">
										<label class="control-label col-md-5 col-sm-5 col-xs-12">
										<?php echo $tr->translate("CON_NUM");?><span class="required">
											</span>
										</label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<div class="input-icon right">
												<i class="fa"></i>
												<?php echo $frm_agent->getElement("phone");?>
											</div>
										</div>
									</div>
									<div class="form-group">
										<label class="control-label col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("EMAIL_ADD");?><span class="required">
											</span>
										</label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<div class="input-icon right">
												<i class="fa"></i>
												<?php echo $frm_agent->getElement("email_detail");?>
											</div>
										</div>
									</div>
					        	</div>
					        	<div class="col-md-6 col-sm-6 col-xs-12">
					        		<div class="form-group">
										<label class="control-label col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("POB");?><span class="required">
												</span>
											</label>
											<div class="col-md-7 col-sm-7 col-xs-12">
												<div class="input-icon right">
													<i class="fa"></i>
													<?php echo $frm_agent->getElement("pob");?>
												</div>
											</div>
									</div>
									<div class="form-group">
										<label class="control-label col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("DOB");?><span class="required">
											</span>
										</label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<div class="input-icon right">
												<i class="fa"></i>
												<?php echo $frm_agent->getElement('dob'); ?>
											</div>
										</div>
									</div>
									<div class="form-group">
										<label class="control-label col-md-5 col-sm-5 col-xs-12">
											<?php echo $tr->translate("CURRENT_ADD");?><span class="required"></span>
										</label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<div class="input-icon right">
												<i class="fa"></i><?php echo $frm_agent->getElement("address");?>
											</div>
										</div>
									</div>
									<div class="form-group">
										<label class="control-label col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("POSITION");?><span class="required">
											</span>
										</label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<div class="input-icon right">
												<i class="fa"></i>
												<?php echo $frm_agent->getElement("job_title");?>
											</div>
										</div>
									</div>
									<div class="form-group">
										<label class="control-label col-md-5 col-sm-5 col-xs-12"><?php echo $tr->translate("DESC");?><span class="required">
											</span>
										</label>
										<div class="col-md-7 col-sm-7 col-xs-12">
											<div class="input-icon right">
												<i class="fa"></i>
												<?php echo $frm_agent->getElement("description");?>
											</div>
										</div>
								</div>
					        	</div>
					        	<div class="clearfix"></div>
					         </div>
					         <!--/.Panel 2-->
					     </div>
					     <!--/. Tab panels -->
					</div>
			                
					<div class="form-body">
						<div class="form-group">
							<label  class="col-md-12 col-md-offset-4 col-md-8">
								<a href="<?php echo $this->baseUrl();?>/rsvacl/user"><button type="button" class="btn red"><i class="fa fa-times"></i> <?php echo $tr->translate("GO_BACK")?></button></a>
								<button type="submit" name="saveclose" value="saveclose" class="btn btn-primary" ><i class="glyphicon glyphicon-log-in"></i> <?php echo $tr->translate("SAVE_CLOSE")?></button>
								<button type="submit" name="btnsavenew" class="btn btn-primary"><i class="fa fa-save"></i> <?php echo $tr->translate("SAVE_NEW")?> </button>
								
							</label>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>
<script>
function readURL(input) {
    if (input.files && input.files[0]) {
        var reader = new FileReader();
        
        reader.onload = function (e) {
            $('#profile_wiew').attr('src', e.target.result);
        }
        reader.readAsDataURL(input.files[0]);
    }
}
var maxSize = 0;
$("#signature").change(function(){
	var iSize = ($("#signature")[0].files[0].size / 1024); 
	
    if (iSize / 1024 > 1) 
    { 
       if (((iSize / 1024) / 1024) > 1) 
       { 
           iSize = (Math.round(((iSize / 1024) / 1024) * 100) / 100);
           alert('<?php echo $tr->translate("Image size more than 5Mb can not upload");?>');
     	   maxSize = 1;
           return false;
           //$("#lblSize").html( iSize + "Gb"); 
       }else{ 
           iSize = (Math.round((iSize / 1024) * 100) / 100);
           if(iSize>5){
               alert('<?php echo $tr->translate("Image size more than 5Mb can not upload");?>');
         	   maxSize = 1;
               return false;
           }
       } 
    } 
    else 
    {
       iSize = (Math.round(iSize * 100) / 100);
       maxSize = 0;
    }
    maxSize = 0;
    readURL(this);
   
});

var index5 = 0;
var option5 = '<?php echo $this->locations; ?>';

var baseUrl = '<?php echo BASE_URL; ?>';
var template = '';
var value = '';
function addRow() {
	index5++;
	template='<tr id="row_order_'+index5+'">';
	var inp = '';
	if(index5 == 1) {
		template+='<td class="quater-input">&nbsp;</td>';
	} else {
		template+='<td class="quater-input"><img onClick="deleteRecord('+index5+')" src="<?php echo BASE_URL; ?>/images/icon/delete.gif" /></td>';
	}
	template+='<td class="quater-input"><select Onchange="AddLocation('+index5+')" class="form-control select2me"  id="location_id_'+index5+'"  name="location_id_'+index5+'" >'+option5+'</select>'+inp+'</td>'; 
	template+="</tr>";
	$('#table_order').append(template);
	if($('#identity').val()!="") {
		var identity = $('#identity').val();
		$('#identity').val(identity+','+index5);
	} else {$('#identity').val(index5);}
	//$("#orderFrm").validationEngine();
	
}

//$('#new_item').click(addRow);

function deleteRecord(index) {
	var identity = $('#identity').val();
	var arrays = identity.split(',');
	for(var i=0;i<arrays.length;i++) {
		if(arrays[i] == index) arrays.splice(i,1);
	}
	var strings = arrays.join(',');
	$('#identity').val(strings);
	$("#row_order_"+index).remove();

}
</script>
