<title>List User </title>
<?php 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$url_new = $this->url(array(
		'module'=>'rsvacl',
		'controller'=>'user',
		'action'=>'add',
	));
	
	$form=$this->form;
	$formfilter=$this->formfilter;
	$url_copy = $this->url(array('module'=>'rsvacl','controller'=>'user','action'=>'copy',),null,true);
	$url_delete = $this->url(array('module'=>'rsvacl','controller'=>'user','action'=>'delete',),null,true);
?>
<div class="row">
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-globe"></i><?php echo $tr->translate("LIST_OF_USER_IN_SYSTEM");?>
				</div>
				<a href="<?php echo $url_new;?>" class="btn btn-sm green  pull-right">
					<i class="fa fa-plus"></i>&nbsp;<?php echo $tr->translate("ADD_NEW");?>
				</a>
				<button onClick="copyRecord('<?php echo $url_copy;?>')" class="btn btn-sm green  pull-right" style="background: #4c0643; margin-right: 5px;">
					<i class="fa fa-plus"></i>&nbsp;<?php echo $tr->translate('COPY');?>
				</button>
				
				<button onClick="DeleteRecord('<?php echo $url_delete;?>')" class="btn btn-sm green  pull-right" style="background: #4c0643; margin-right: 5px;">
					<i class="fa fa-trash"></i>&nbsp;<?php echo $tr->translate('DELETE');?>
				</button>
				
			</div>
			<div class="portlet-body form frmfilter">
				<form method="post" action="">
					<div class="form-group" style="padding-top: 6px;">
						<label class="control-label col-md-3"><?php echo $formfilter->getElement('ad_search');?></label>
						<label class="control-label col-md-3"><?php echo $formfilter->getElement('location');?></label>
						<label class="control-label col-md-3"><?php echo $formfilter->getElement('user_type_filter');?></label>
						<label class="control-label col-md-3"><?php echo $formfilter->getElement('status_se');?></label>
						<label class="control-label col-md-3">
							<button class="btn btn-primary col-md-12" value="" ><i class="fa fa-save"></i>&nbsp;<?php echo $tr->translate("REFRESH");?></button>
						</label>
					</div>			
				</form> 
				<div class="contain_form" style="clear: both;">
						<?php echo  $this->form;?>
			    </div>
		   </div>
		</div>
	</div>
</div><script>
//url = <?php echo $url_copy;?>;
function copyRecord(url) {
	//alert(1);
	 var cbs = $("input:checkbox"); //find all checkboxes
	 var nbCbs = cbs.size(); //the number of checkboxes
	 var checked = $("input[type=checkbox]:checked"); //find all checked checkboxes + radio buttons
	 var nbChecked = checked.size();
	 if(nbChecked < 1) {
	  alert("Please select record to copy!");
	 } else {
	  /*var answer = confirm("Are you sure you want to delete it?")
	     if (answer){*/
	   id = new Array();
	   var i = 0;
	   checked.each(function() {
	    id[i] = $(this).val();
	    i++;
	   });
	   window.location.href = url+'/id/'+id;
	     /*} else {
	      alert("Sorrty can't delete it!");
	     }*/
	 }
	}
function DeleteRecord(url) {
	//alert(1);
	 var cbs = $("input:checkbox"); //find all checkboxes
	 var nbCbs = cbs.size(); //the number of checkboxes
	 var checked = $("input[type=checkbox]:checked"); //find all checked checkboxes + radio buttons
	 var nbChecked = checked.size();
	 if(nbChecked < 1) {
	  alert("Please select record to copy!");
	 } else {
	  var answer = confirm("Are you sure you want to delete it?")
	     if (answer){
	   id = new Array();
	   var i = 0;
	   checked.each(function() {
	    id[i] = $(this).val();
	    i++;
	   });
	   window.location.href = url+'/id/'+id;
	     } else {
	      alert("Sorrty can't delete it!");
	     }
	 }
	}
</script>