<?php 
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$form=$this->form;
	$url_submit = $this->url(array('module'=>'purchase','controller'=>'index','action'=>'add'));
	$url_cancel = $this->url(array('module'=>'purchase','controller'=>'index','action'=>'index'),null,true);
?>
<style>
      table.table-bordered tbody th, table.table-bordered tbody td{width:2px;}
</style>
<title><?php echo $tr->translate("ADD_PURCAHSE_ORDER");?></title>
<div class="row">
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="icon-home"></i><?php echo $tr->translate("ADD_PURCAHSE_ORDER")?>
				</div>
				<div class="tools" >
					<a href="<?php echo $url_cancel;?>" class="btn btn-sm pull-right" style="color:white;">
					<i class="fa fa-undo"></i>	&nbsp;<?php echo $tr->translate("GO_BACK");?>
					</a>
				</div>
			</div>
			<div class="portlet-body form">
				<!-- BEGIN FORM-->
				<form id="frm" action="<?php //echo $url_submit; ?>" class="form-horizontal" enctype="multipart/form-data" method="post">
					<div class="form-body">
						<div class="form-group">
							<label class="control-label col-md-2"><?php echo $tr->translate("REQUEST_CODE");?> <span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $form->getElement("request_no");?>
								</div>
							</div>
							<label class="control-label col-md-2"><?php echo $tr->translate("LOCATION_NAME");?><span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $form->getElement('branch');?>
								</div>
							</div>
						</div>
						<div class="form-group">
							<label class="control-label col-md-2"><?php echo $tr->translate("REMARK");?> <span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $form->getElement("remark");?>
								</div>
							</div>
							<label class="control-label col-md-2"><?php echo $tr->translate("STATUS");?><span class="required">
								</span>
							</label>
							<div class="col-md-4">
								<div class="input-icon right">
									<i class="fa"></i>
									<?php echo $form->getElement('status');?>
								</div>
							</div>
						</div>
						<div class="form-group">
						<div class="col-md-12">
							<label class="control-label col-md-2 col-lg-2">
								<button type="button" class="btn red delete col-md-12">
									<i class="fa fa-barcode"></i>
									<span>Scan </span>	
								</button>
							</label>
							<label class="control-label col-md-8">
								<select data-placeholder="Select..." class="form-control select2me " style="text-align: left;" id="add_item" name="add_item" Onchange="getItemOrder();" >
								<?php echo $this->items; ?>
								</select>
							</label>
							<label class="control-label col-md-2 col-lg-2 col-sm-12">
								<button type="button" class="btn red delete col-md-12">
								<!-- 	<input type="checkbox" Onclick="Confirmmessage()" id="free" name="free" />
									<span>&nbsp;&nbsp;Free</span>
									-->
								</button> 
							</label>
						</div>
						</div>
						<div class="portlet-body">
							<table class="table table-striped table-bordered table-hover" id="table_order" style="font-size:12px;">
								<tr height="33px">
									<td style="width:4%;" class="center"><?php echo $tr->translate("DEL");?></td>
									<td style=" width:4%;" class="center"><?php echo $tr->translate("NUM");?></td>
									<td style="white-space:nowrap;" class="center"><?php echo $tr->translate("ITEM_NAME_CAP");?></td>
									<td style="white-space:nowrap;" class="center"><?php echo $tr->translate("QTY_UNIT");?></td>
									<td style="white-space:nowrap;" class="center"><?php echo $tr->translate("REMARK");?></td>
								</tr>
							</table>
							<input type="hidden" id="identity" name="identity" />
							
						</div>
						
						<div class="form-group">
							<label  class="col-md-12 col-md-offset-4 col-md-8">
								<a href="<?php echo $this->baseUrl();?>/purchase/purchaserequest/"><button type="button" class="btn red"><i class="fa fa-times"></i> <?php echo $tr->translate("EXIT")?></button></a>
								<button type="submit" name="save_close" value="saveclose" class="btn btn-primary" ><i class="glyphicon glyphicon-log-in"></i> <?php echo $tr->translate("SAVE_CLOSE")?></button>
								<button type="submit" name="btnsavenew" class="btn btn-primary"><i class="fa fa-save"></i> <?php echo $tr->translate("SAVE_NEW")?> </button>
								<button type="submit" name="save_print" class="btn btn-primary"><i class="fa fa-print"></i> <?php echo $tr->translate("SAVE_PRINT")?></button>
							</label>
						</div>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>
<script>
$(document).ready(function() {
	initList();
	//initListTermcondition();
});
var index5 = 0;num=0;
var option5 = '<?php echo $this->items; ?>';
var baseUrl = '<?php echo BASE_URL; ?>';
var template = '';
var value = '';
pqty = 1;
var index=0;
function addRow(item_id) {
	index5++; //var first = index5;
	for(i=1; i<index5; i++){
		new_item=parseInt(item_id);
		items = parseInt($("#item_id_"+i).val());
		if(new_item==items){		
			newqty = parseInt($("#qty_"+i).val());
			newqty = newqty+1;
			$("#qty_"+i).val(newqty);
			return false;
		}
	}
	template='<tr id="row_order_'+index5+'" style="height:33px;">';
	var inp = '';
	if(index5 == 1) {
		template+='<td width="2%" class="center">&nbsp;</td>';
	} else {
		template+='<td width="2%" class="center"><img onClick="deleteRecord('+index5+')" src="<?php echo BASE_URL; ?>/images/icon/delete.gif" /></td>';
	}
	template+='<td width="2%" class="center">'+index5+'</td>';
	template+='<td><select class="form-control select2me" Onchange="ShowPopupProduct('+ index5 + ');" id="item_id_'+index5+'" name="item_id_'+index5+'" >'+option5+'<option></option></select>'+inp+'</td>';
	template+='<td><input type="text" class="form-control" required="1" id="qty_'+index5+'" name="qty_'+index5+'" value="1"/></td>';
	template+='<td><input type="text" class="form-control" id="remark_'+index5+'" name="remark_'+index5+'" /></span></td>';
	template+="</tr>";
	$('#table_order').append(template);
	//$('#item_id_'index5).select2me();
	if($('#identity').val()!="") {
		var identity = $('#identity').val();
		$('#identity').val(identity+','+index5);
	} else {$('#identity').val(index5);}
	$("#item_id_"+index5).val(item_id);
	$("#row_order_0").remove();
	
}
function initList() {
	index5=0;
	var template;
	var option5 = '<?php echo $this->items;?>';
	<?php if(!empty($this->item)) {
		foreach($this->item AS $i=>$r){?>
	index5++; 
	index=index+1;
	template='<tr id="row_order_'+index5+'" style="height:33px;">';
	var inp = '';
	if(index5 == 1) {
		template+='<td width="2%" class="center">&nbsp;</td>';
	} else {
		template+='<td width="2%" class="center"><img onClick="deleteRecord('+index5+')" src="<?php echo BASE_URL; ?>/images/icon/delete.gif" /></td>';
	}
	template+='<td width="2%" class="center">'+index5+'</td>';
	template+='<td><select class="form-control select2me" Onchange="ShowPopupProduct('+ index5 + ');" id="item_id_'+index5+'" name="item_id_'+index5+'" >'+option5+'<option></option></select>'+inp+'</td>';
	template+='<td><input type="text" class="form-control" required="1" id="qty_'+index5+'" name="qty_'+index5+'" value="1"/></td>';
	template+='<td><input type="text" class="form-control" id="remark_'+index5+'" name="remark_'+index5+'" /></span></td>';
	template+="</tr>";
	$('#table_order').append(template);
	
	$("#item_id_"+index5).val("<?php echo $r['pro_id'];?>");
	$("#qty_"+index5).val("<?php echo $r['qty'];?>");
	
	//getQtyById(index5);
	

	if($('#identity').val()!="") {
		var identity = $('#identity').val();
		$('#identity').val(identity+','+index5);
	} else {$('#identity').val(index5);}
	
	$("#row_order_0").remove();
		<?php } }?>
}
function getItemOrder(){
	item_ids=$("#add_item").val();
	$('#add_item').val('').trigger("liszt:updated");
	if(item_ids==-1){
		return false;
	}
	addRow(item_ids);
	$("#add_item").val("");
}
</script>