<?php 					
	$url_new = $this->url(array('module'=>'purchase','controller'=>'requestpurchasing','action'=>'add',));
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$formFilter = $this->formFilter;
	//print_r($this->rs);
?>

<title><?php echo $tr->translate("TRANSFER_STOCK");?></title>
<?php 
	$url_new = $this->url(array('module'=>'purchase','controller'=>'requestpurchasing','action'=>'add',));
	//$url_delete = $this->url(array('module'=>'product','controller'=>'index','action'=>'delete-product',));
	$formFilter = $this->formFilter;
?>

<title><?php echo $tr->translate("TRANSFER_STOCK");?></title>
<meta charset="utf-8" />
<div class="row">
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-globe"></i><?php echo $tr->translate("TRANSFER_STOCK");?>
				</div>
				 
			</div>
			<div class="portlet-body form frmfilter">
				<form method="post" action="<?php echo $formFilter->getAction(); ?>">
					<div class="form-group" style="padding-top: 6px;">
						<label class="control-label col-md-3"><?php echo $formFilter->getElement('text_search');?></label>
						<label class="control-label col-md-3"><?php echo $formFilter->getElement('branch_id');?></label>
						<label class="control-label col-md-3"><?php echo $formFilter->getElement('suppliyer_id');?></label>
						<label class="control-label col-md-3"><?php echo $formFilter->getElement('status_paid');?></label>
					</div>
					<div class="form-group" style="padding-top: 6px;">
						<label class="control-label col-md-3"><?php echo $formFilter->getElement('purchase_status');?></label>
						<label class="control-label col-md-3"><div class="input-icon right"><i class="fa fa-calendar"></i><?php echo $formFilter->getElement('start_date');?></div></label>
						<label class="control-label col-md-3"><div class="input-icon right"><i class="fa fa-calendar"></i><?php echo $formFilter->getElement('end_date');?></div></label>
						<label class="control-label col-md-2">
							<button class="btn btn-primary col-md-12" value="" ><i class="fa fa-save"></i>&nbsp;<?php echo $tr->translate("REFRESH");?></button>
						</label>
					</div>				
				</form> 
				<div class="contain_form" style="clear: both;">
					<form name="list"><div style="overflow:scroll; max-height: 450px; overflow-x:hidden;" >
					<table class="collape tablesorter" id="table" width="100%">
						<thead>
							<tr>
								<th class="tdheader"><?php echo  $tr->translate("NUM");?></th>
								<th class="tdheader"><?php echo  $tr->translate("BRANCH_NAME");?></th>
								<th class="tdheader"><?php echo  $tr->translate("VENDOR_NAME");?></th>
								<th class="tdheader"><?php echo  $tr->translate("REQUEST_NUMBER");?></th>
								<th class="tdheader"><?php echo  $tr->translate("REQUEST_DATE");?></th>
								<th class="tdheader"><?php echo  $tr->translate("DATE_IN");?></th>
								<th class="tdheader"><?php echo  $tr->translate("TOTAL_AMOUNT");?></th>
								<th class="tdheader"><?php echo  $tr->translate("PAID");?></th>
								<th class="tdheader"><?php echo  $tr->translate("BALANCE");?></th>
								<th class="tdheader"><?php echo  $tr->translate("ORDER_STATUS");?></th>
								<th class="tdheader" ><?php echo  $tr->translate("ACTION");?></th>
								<th class="tdheader"><?php echo  $tr->translate("STATUS");?></th>
							</tr>
						</thead>
						<tbody>
							<?php 
							$id = "table";
							$stringPagination = '<script type="text/javascript">
										$(document).ready(function(){
											$("#'.$id.'").tablesorter();
											$("#'.$id.'").tablesorter().tablesorterPager({container: $("#pagination_'.$id.'"),size:15});
											$("#pagedisplay").focus(function(){ this.blur(); 
										   });
										});
								</script>
								<div id="pagination_'.$id.'" class="pager" >
											<form >
												<table  style="width: 200px;"><tr>
												<td><img src="'.BASE_URL.'/images/first.gif" class="first"/></td>
												<td><img src="'.BASE_URL.'/images/previous.gif" class="prev"/></td>
												<td><input type="text" class="pagedisplay"/></td>
												<td><img src="'.BASE_URL.'/images/next.gif" class="next"/></td>
												<td><img src="'.BASE_URL.'/images/last.gif" class="last"/></td>
												<td><select class="pagesize" >
													<option selected="selected"  value="10">10</option>
													<option value="20">20</option>
													<option value="30">30</option>
													<option value="40">40</option>
													<option value="50">50</option>
													<option value="60">60</option>
													<option value="70">70</option>
													<option value="80">80</option>
													<option value="90">90</option>
													<option value="100">100</option>
													</select>
												</td>
												</tr>
												</table>
											</form>
									</div>	';
							$footer="";
							if(!empty($this->rs)){
								foreach ($this->rs as $key=>$rs){
									$edit_status = '';
									if($rs["purchase_status"]==1){ //$rs["pedding_stat"]>3
										$edit_status = "style='pointer-events: none;cursor: default;color: #ccc;'";
									}
							?>
								<tr class="normal">
									<td class="items-no"><?php echo $key+1;?></td>
									<td class="items"><?php echo $rs["branch_name"];?></td>
									<td class="items"><?php echo $rs["vendor_name"];?></td>
									<td class="items"><?php echo $rs["order_number"];?></td>
									<td class="items"><?php echo date('d-M-Y',strtotime($rs["date_order"]));?></td>
									<td class="items"><?php echo date('d-M-Y',strtotime($rs["date_in"]));?></td>
									<td class="items"><?php echo $rs["net_total"];?></td>
									<td class="items"><?php echo $rs["paid"];?></td>
									<td class="items"><?php echo $rs["balance"];?></td>
									<td class="items"><?php echo $rs["purchase_statuss"];?></td>
									<td class="items-no" style="white-space: nowrap;">
										<a <?php echo $edit_status;?> href="<?php echo $this->baseUrl();?>/purchase/mrapprove/approve/id/<?php echo $rs["id"]?>"><?php echo  $tr->translate("CHECK");?></a> | 
										<a target="_blank" href="<?php echo $this->baseUrl();?>/report/purchase/requestpurchasing/id/<?php echo $rs["id"]?>"><?php echo  $tr->translate("PRINT");?></a>
									</td>
									<td class="items"><?php echo $rs["status"];?></td>
								</tr>
							<?php $counter='<strong style="float:right;padding:5px">Number of record(s): '.count($this->rs).'</strong>'; 
								$footer = '<div class="footer_list">'.$stringPagination.$counter.'</div>';
							}}?>
						</tbody>
					</table></div></form><?php echo $footer?>
						<?php //echo $this->list; ?>
			    </div>
		   </div>
		</div>
	</div>
</div>
<script>
$( document ).ready(function() {
   // $("#plan").val('<?php echo $this->search['plan']?>');
    //$("#branch").val('<?php echo $this->search['branch']?>');
});
</script>