<?php 
$user_info = new Application_Model_DbTable_DbGetUserInfo();
$result = $user_info->getUserInfo();
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$session_user=new Zend_Session_Namespace('auth');
$request=Zend_Controller_Front::getInstance()->getRequest();

$session_lang=new Zend_Session_Namespace('lang');
$currentLang=$session_lang->lang_id;
?>
<style>
.page-header.navbar .top-menu .navbar-nav > li.dropdown .dropdown-toggle .badge.badge-default {
    background-color: #fa3e3e;
}
</style>
	<div class="page-header-inner">
		<!-- BEGIN LOGO -->
		<div class="page-logo text-center">
			<a title="<?php echo $tr->translate("Cam App Technology");?>" href="<?php echo $this->baseUrl(); ?>/default/index/dashboad">
				<img style=" width: 120px; padding: 4px 0;" src="<?php echo $this->baseUrl()."/images/cam-app-logo.png"?>" alt="<?php echo $tr->translate("Cam App Technology");?>" />
			</a>
			<div class="menu-toggler sidebar-toggler hide">
				<!-- DOC: Remove the above "hide" to enable the sidebar toggler button on header -->
			</div>
		</div>
		<!-- END LOGO -->
		<!-- BEGIN RESPONSIVE MENU TOGGLER -->
		<a href="javascript:;" class="menu-toggler responsive-toggler" data-toggle="collapse" data-target=".navbar-collapse">
		</a>
		
		<!-- END RESPONSIVE MENU TOGGLER -->
		<!-- BEGIN TOP NAVIGATION MENU -->
		<div class="top-menu">
			<ul class="nav navbar-nav pull-right">
			
			
			<li class="dropdown dropdown-extended dropdown-inbox" id="header_inbox_bar">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
					<i class="icon-envelope-open"></i>
					<span class="badge badge-default">
					<?php 
					    $dbtable = new Product_Model_DbTable_DbGetBranch();
						$num = $dbtable->getSumNumProduct($session_user->user_id);
						echo $num;
					?></span>
					</a>
					<ul class="dropdown-menu">
						<li class="external">
							<h3><a  target="_blank" href="<?php echo $this->url(array('module'=>'report','controller'=>'product','action'=>'rpt-procut-qtywarning'));?>"><span class="bold">You have <?php echo $num;?>product  quantity​​ in stock not enough!!!</span></a> </h3>
						</li>
						<li>
							<ul class="dropdown-menu-list scroller" style="height: 275px;" data-handle-color="#637283">
								<li>
									<a target="_blank" href="<?php echo $this->url(array('module'=>'report','controller'=>'product','action'=>'rpt-procut-qtywarning'));?>">
									<span class="photo">
									</span>
									<span class="subject">
									<span class="from">
									<?php echo $tr->translate("COMPANY_CUSTOMER");?> </span>
									<span class="time">Just Now </span>
									</span>
									<span class="message">
									List product in stock... </span>
									</a>
								</li>
						
							</ul>
						</li>
					</ul>
				</li>
				
				<!-- BEGIN INBOX DROPDOWN -->
				<!-- DOC: Apply "dropdown-dark" class after below "dropdown-extended" to change the dropdown styte -->
				<li style="display: none;" class="dropdown dropdown-extended dropdown-inbox" id="header_inbox_bar">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
					<i class="icon-envelope-open"></i>
					<span class="badge badge-default">
					4 </span>
					</a>
					<ul class="dropdown-menu" >
						<li class="external">
							<h3>You have <span class="bold">7 New</span> Messages</h3>
							<a href="page_inbox.html">view all</a>
						</li>
						<li>
							<ul class="dropdown-menu-list scroller" style="height: 275px;" data-handle-color="#637283">
								<li>
									<a href="inbox.html?a=view">
									<span class="photo">
									</span>
									<span class="subject">
									<span class="from">
									Richard Doe </span>
									<span class="time">46 mins </span>
									</span>
									<span class="message">
									Vivamus sed congue nibh auctor nibh congue nibh. auctor nibh auctor nibh... </span>
									</a>
								</li>
							</ul>
						</li>
					</ul>
				</li>
				<!-- END INBOX DROPDOWN -->
				<!-- BEGIN TODO DROPDOWN -->
				<!-- DOC: Apply "dropdown-dark" class after below "dropdown-extended" to change the dropdown styte -->
				<li class="dropdown dropdown-extended dropdown-tasks" id="header_task_bar">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
					<i class="icon-calendar"></i>
					<span class="badge badge-default">
					 <?php 
									$dbtable = new Product_Model_DbTable_DbGetBranch();
									$branchs = $dbtable->getBranchbyUser($session_user->user_id);
									echo count($branchs);
						?></span>
					</a>
					<ul class="dropdown-menu extended tasks">
						<li class="external">
							<h3>You can access <span class="bold"><?php echo count($branchs);?></span> Location(s)</h3>
						</li>
						<li>
							<ul class="dropdown-menu-list scroller" style="height: 275px;" data-handle-color="#637283">
									<?php if(!empty($branchs)) foreach ($branchs as $key =>$value){?>
								  <li>
										<a href="<?php echo $this->url(array('module'=>'product','controller'=>'changeuser','action'=>'index', 'id'=>$value["location_id"]));?>">
											<span class="task">
												<span class="desc">Location : <?php echo $value["name"]?></span>
											</span>
										</a>
									</li>
								<?php };?>
							</ul>
						</li>
					</ul>
				</li>
				<?php 
				$images = $this->baseUrl().'/images/profile.png';
				if($session_user->user_img !=''){
				       $img=$session_user->user_img ;
				       if (file_exists(PUBLIC_PATH.'/images/user/'.$img)) {
				       	$images = $this->baseUrl().'/images/user/'.$img;
				       }
				}?>
				<!-- END TODO DROPDOWN -->
				<!-- BEGIN USER LOGIN DROPDOWN -->
				<!-- DOC: Apply "dropdown-dark" class after below "dropdown-extended" to change the dropdown styte -->
				<li class="dropdown dropdown-user">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
					<img alt="" class="img-circle" src="<?php echo $images;?>"/>
					<span class="username username-hide-on-mobile">
					<?php echo $session_user->fullname;?> </span>
					<i class="fa fa-angle-down"></i>
					</a>
					<ul class="dropdown-menu dropdown-menu-default">
						<!-- <li>
							<a href="#">
							<i class="icon-user"></i> My Profile </a>
						</li>
						<li>
							<a href="#">
							<i class="icon-calendar"></i> My Calendar </a>
						</li>
						<li>
							<a href="#">
							<i class="icon-envelope-open"></i> My Inbox <span class="badge badge-danger">
							3 </span>
							</a>
						</li>
						<li>
							<a href="#">
							<i class="icon-rocket"></i> My Tasks <span class="badge badge-success">
							7 </span>
							</a>
						</li> -->
						<li class="divider">
						</li>
						<!-- <li>
							<a href="<?php //echo $this->url(array("module"=>"default","controller"=>"index","action"=>"index"));?>">
							<i class="icon-lock"></i> Lock Screen </a>
						</li> -->
						<li>
							<a href="<?php echo $this->baseUrl()."/index/logout/value/1";//echo $this->url(array("module"=>"default","controller"=>"index"));?>">
							<i class="icon-key"></i> <?php echo $tr->translate("Log Out")?> </a>
						</li>
					</ul>
				</li>
				<!-- END USER LOGIN DROPDOWN -->
				<li class="dropdown dropdown-extended dropdown-tasks" id="header_task_bar">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true" style=" padding: 3px;">
						<?php if ($currentLang == 1){
							$flage = $this->baseUrl()."/images/km.png";
						}else{
							$flage = $this->baseUrl()."/images/en.jpg";
						}?>
						<img src="<?php echo $flage;?>" style=" width: 40px; height: 40px; border-radius: 50% !important;" />
					</a>
					<ul class="dropdown-menu extended tasks">
						<li>
							<ul class="dropdown-menu-list scroller" style="height: 275px;" data-handle-color="#637283">
								<li>
									<a onclick="changeLange(1);" href="#" style=" padding: 4px 10px; background: #f5f5f5; color: #02014a;">
									<span class="task">
									<span class="desc" style="font-weight: 600;">
										<img src="<?php echo $this->baseUrl()."/images/km.png";;?>" style=" width: 40px; height: 40px; border-radius: 50% !important;" /> 
										<?php echo $tr->translate("Khmer")?>
									</span>
									</span>
									</a>
								</li>
								<li>
									<a onclick="changeLange(2);" href="#" style=" padding: 4px 10px; background: #f5f5f5; color: #02014a;">
									<span class="task">
									<span class="desc" style="font-weight: 600;">
										<img src="<?php echo $this->baseUrl()."/images/en.jpg";;?>" style=" width: 40px; height: 40px; border-radius: 50% !important;" /> 
										<?php echo $tr->translate("English")?>
										</span>
									</span>
									</a>
								</li>
							</ul>
						</li>
					</ul>
				</li>
			</ul>
		</div>
		<!-- END TOP NAVIGATION MENU -->
	</div>
	<!-- END HEADER INNER -->
	<script>	
var url_changelang = '<?php echo $this->url(array('module'=>'default','controller'=>'index','action'=>'changelange'));?> ';
function changeLange(lang){
	$.ajax({
		url:url_changelang,
		type:"post",
		data:{'lange':lang,},
		success: function(data){
			location.reload();
		},
		error:function(e){
			alert(e);
		}
	});
}
		
	</script>