<?php 
	$url_new = $this->url(array('module'=>'product','controller'=>'branch','action'=>'add',));
	$url_edit = $this->url(array('module'=>'product','controller'=>'branch','action'=>'edit',));
	$url_close = $this->url(array('module'=>'product','controller'=>'branch','action'=>'index',));
	$url_delete = $this->url(array('module'=>'product','controller'=>'branch','action'=>'delete',));
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$formFilter = $this->frmAdd;
?>
<title><?php echo $tr->translate("EDIT_LOCATION");?></title>
<style>
.image-box {
    text-align: center;
}
.image-box img {
    width: 200px;
    height: 190px;
    border: solid 1px #eee;
}
.button_browse {
    /*margin-top: 10px; */
    position: relative;
    overflow: hidden;
    text-align: center;
    width: 100%;
    height: 45px;
    cursor: pointer;
    background: #fbf9f9;
    border: 1px solid #e8e8e8;
}
.button_browse span {
    line-height: 40px;
    font-weight: 600;
    cursor: pointer;
}
input.btn_borwse_image {
    position: absolute;
    width: 100%;
    height: 45px;
    top: 0;
    left: 0;
    z-index: 2;
    opacity: 0;
    cursor: pointer;
}
.account-image {
    border: solid 1px #eee;
    width: 200px;
}
</style>
<div class="col-md-12">
	<div class="portlet box blue">
		<div class="portlet-title">
			<div class="caption">
					<i class="fa fa-globe"></i><?php echo $tr->translate("EDIT_LOCATION");?>
			</div>
			<div class="tools">
				<a href="<?php echo $url_close;?>"><button type="button" name="calcel" class="btn red"><?php echo $tr->translate("GO_BACK");?></button></a>
			</div>
		</div>
		<div class="portlet-body form">
			<form class="form-horizontal" method="post" action="<?php echo $url_edit;?>" enctype="multipart/form-data"  >
				<div class="form-body">
							<div class="form-group">
								<label class="col-md-2 control-label"><?php echo $tr->translate("BRANCH_NAME");?></label>
								<div class="col-md-4">
									<?php echo $formFilter->getElement('branch_name');?>
								</div>
												
								<label class="col-md-2 control-label"><?php echo $tr->translate("COMPANY_NAME");?></label>
								<div class="col-md-4">
									<?php echo $formFilter->getElement('code');?>
								</div>
							</div>
											
							<div class="form-group">
								<label class="col-md-2 control-label"><?php echo $tr->translate("CON_NAME");?></label>
								<div class="col-md-4">
									<?php echo $formFilter->getElement('contact');?>
								</div>
								<label class="col-md-2 control-label"><?php echo $tr->translate("PREFIX");?></label>
								<div class="col-md-4">
									<?php echo $formFilter->getElement('prefix');?>
								</div>
							</div>
							<div class="form-group">					
								<label class="col-md-2 control-label"><?php echo $tr->translate("PHONE_NUM");?></label>
								<div class="col-md-4">
									<?php echo $formFilter->getElement('contact_num');?>
								</div>
								
								<label class="col-md-2 control-label"><?php echo $tr->translate("Office Phone");?></label>
								<div class="col-md-4">
									<?php echo $formFilter->getElement('office_num');?>
								</div>
							</div>
							<div class="form-group">
								<label class="col-md-2 control-label"><?php echo $tr->translate("EMAIL");?></label>
								<div class="col-md-4">
									<?php echo $formFilter->getElement('email');?>
								</div>
												
								<label class="col-md-2 control-label"><?php echo $tr->translate("FAX");?></label>
								<div class="col-md-4">
									<?php echo $formFilter->getElement('fax');?>
								</div>
							</div>
							
							<div class="form-group">
								
								<label class="col-md-2 control-label"><?php echo $tr->translate("ADD_LOCATION");?></label>
								<div class="col-md-4">
									<?php echo $formFilter->getElement('address');?>
								</div>
								<label class="col-md-2 control-label"><?php echo $tr->translate("REMARK");?></label>
								<div class="col-md-4">
									<?php echo $formFilter->getElement('remark');?>
								</div>
								
												
								
							</div>
							<div class="form-group">
								<label class="col-md-2 control-label"><?php echo $tr->translate("LOGO");?></label>
								<div class="col-md-4">
									<div class="input-group">
									<?php //echo $formFilter->getElement('logo');?>
									<?php //echo $formFilter->getElement('old_logo');?>
									</div>
									
									<?php 
										$images = $this->baseUrl().'/images/no_images.jpg';
										if (!empty($this->rs['logo'])){
											if (file_exists(PUBLIC_PATH.'/images/logo/'.$this->rs['logo'])) {
												$images = $this->baseUrl().'/images/logo/'.$this->rs['logo'];
											}
												
										}
										?>
										<input name="old_photo"  value="<?php echo $this->rs['logo'];?>" type="hidden" />
										<div class="account-image" >
											<div class="image-box">
												<img id="profile_wiew" src="<?php echo $images;?>" alt=""  />
											</div>
											<div class="button_browse">
											<div id='preview'></div>	
													<span>Upload <span ><i class="fa fa-camera" aria-hidden="true"></i></span></span>
													<input class="btn_borwse_image" type="file" id="logo" name="logo" />
											</div>
										</div>
								</div>
								<div class="col-md-6">
									<div class="form-group">
										<label class="col-md-4 control-label"><?php echo $tr->translate("SHOW_BY");?></label>
										<div class="col-md-8">
											<?php echo $formFilter->getElement('show_by');?>
										</div>
									</div>
									<div class="form-group">
										<label class="col-md-4 control-label"><?php echo $tr->translate("STATUS");?></label>
										<div class="col-md-8">
											<?php echo $formFilter->getElement('status');?>
										</div>
									</div>
								</div>
							</div>
							
							<div class="form-group">
								<label class="col-md-2 control-label"><?php echo $tr->translate("STATUS");?></label>
								<div class="col-md-4">
									<?php echo $formFilter->getElement('status');?>
								</div>
							</div>
						<div class="form-group">
								<label  class="col-md-12 col-md-offset-4 col-md-8">
									<a href="<?php echo $this->baseUrl();?>/branch/index"><button type="button" class="btn red"><i class="fa fa-times"></i> <?php echo $tr->translate("GO_BACK")?></button></a>
									<button type="submit" name="save_close" value="saveclose" class="btn btn-primary" ><i class="glyphicon glyphicon-log-in"></i> <?php echo $tr->translate("GO_EDIT")?></button>
								</label>
						</div>
						
					</div>
					</form>
				</div>
		</div>
	</div>
</div>
<script>
function readURL(input) {
    if (input.files && input.files[0]) {
        var reader = new FileReader();
        
        reader.onload = function (e) {
            $('#profile_wiew').attr('src', e.target.result);
        }
        reader.readAsDataURL(input.files[0]);
    }
}
var maxSize = 0;
$("#logo").change(function(){
	var iSize = ($("#logo")[0].files[0].size / 1024); 
	
    if (iSize / 1024 > 1) 
    { 
       if (((iSize / 1024) / 1024) > 1) 
       { 
           iSize = (Math.round(((iSize / 1024) / 1024) * 100) / 100);
           alert('<?php echo $tr->translate("Image size more than 5Mb can not upload");?>');
     	   maxSize = 1;
           return false;
           //$("#lblSize").html( iSize + "Gb"); 
       }else{ 
           iSize = (Math.round((iSize / 1024) * 100) / 100);
           if(iSize>5){
               alert('<?php echo $tr->translate("Image size more than 5Mb can not upload");?>');
         	   maxSize = 1;
               return false;
           }
       } 
    } 
    else 
    {
       iSize = (Math.round(iSize * 100) / 100);
       maxSize = 0;
    }
    maxSize = 0;
    readURL(this);
   
});
</script>