<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$session_user=new Zend_Session_Namespace('auth');
	$user_id=$session_user->user_id;
	$originalDate = "2012-10-31";
	$newDate = date("m/d/Y", strtotime($originalDate));
?>
<form  id='foundation_class' action=""  method="post" enctype="application/x-www-form-urlencoded">
</form>
<style>
.hover:hover{ background: #ddd;}
</style>
<title><?php echo $tr->translate("RPT_EXPENSE");?></title>
<div class="row">
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-globe"></i><?php echo $tr->translate("RPT_EXPENSE");?>
				</div>
				<div class="btn-group pull-right">
						 <?php 	echo $this->render('printbutton.phtml');?>
				</div>
			</div>
 <div class="portlet-body form frmfilter">
	<form method="post" action="<?php //echo $formFilter->getAction(); ?>">
		<div class="form-group" style="padding-top: 6px;">
			<?php $formFilter = $this->formFilter; ?>
			<label class="control-label col-md-3"><?php echo $formFilter->getElement('text_search');?></label>
			<label class="control-label col-md-3"><?php echo $formFilter->getElement('branch_id');?></label>
			<label class="control-label col-md-3"><?php echo $formFilter->getElement('title');?></label>
			<label class="control-label col-md-3"><div class="input-icon right"><i class="icon-calendar"></i><?php echo $formFilter->getElement('start_date');?></div></label>
		</div><div style="clear:both;"></div>	
		
		<div class="form-group" style="padding-top: 6px;">
			<label class="control-label col-md-3"><div class="input-icon right"><i class="icon-calendar"></i><?php echo $formFilter->getElement('end_date');?></div></label>
			<label class="control-label col-md-3">
				<button class="btn btn-primary col-md-12" value="" ><i class="fa fa-save"></i>&nbsp;<?php echo $tr->translate("REFRESH");?></button>
			</label>
		</div><div style="clear:both;"></div>	
		
	</form> 
</div>
<div style="min-height:26cm; margin:0 auto; padding:0.2cm 0.2cm 0cm 0.2cm">
	<div id="divPrint"  >
			<style>
				.style{
					line-height: 20px;font-size: 11px !important;
					font-family: 'Khmer OS Battambang';
				}
				ul{margin: 0;padding:0;}
				table tr td ul li{text-align: center;list-style: none;line-height: 25px; font-weight: bold;}
				th{padding: 5px;}
				.hover:hover{background: #ccc;}
			</style>
		<table class="table2excel" style="background:#fff; margin: 0 auto; width: 100%; padding: 0px 2px 1cm 2px;font-family: 'Khmer OS Battambang';" >
		<tr style="font-size: 13px;">
		    <td width="25%" valign="top"><img src="<?php echo $this->baseUrl();?>/images/logo.jpg" height="85px"></td>
			<td   width="50%" valign="top" align="center">
				<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 14px;font-family:'Khmer MEF2';"><?php echo $tr->translate("COMPANY_CUSTOMER");?></strong><br />
				<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 14px;font-family:'Khmer MEF2';"><?php echo $tr->translate("RPT_EXPENSE");?></strong><br />
				<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 13px;font-family:'Khmer MEF2';"><?php if (!empty($this->search["start_date"])){?> For Date <?php echo date("d-M-Y",strtotime($this->search["start_date"]))?> to <?php echo date("d-M-Y",strtotime($this->search["end_date"]));} ?></strong>
			</td>
			<td width="25%"></td>
		</tr>
		<tr>
			<td width="20%" align="left">
			</td>
			<td align="center">
				<strong style="font-weight:bold;font-family: Arial Black;color:#000; font-size: 13px;font-family:'Khmer MEF2';"></strong>
			</td>
			<td align="right" width="20%">&nbsp;</td>
		</tr>
		<?php 
			$total_income_kh=0;
			$total_income_dollar=0;
			$total =0;
			$total_paid =0;
			$total_expense_kh=0;
			$total_expense_dollar=0;
		?>
		<tr>
			<td colspan="3">
		 	 <table class="table2excel" border="1"​ style="border-collapse:collapse;border:1px solid #000; font-size:12px;" width="100%" cellspacing="0">
           		<thead>
	                <tr bgcolor="#c1d0f3" class="style" align="center" style="font-weight:bold;line-height: 30px; font-size:12px; padding:1px 0px; white-space: nowrap; ">
	                    <td style="border: 1px solid #000;">&nbsp;<?php echo $tr->translate('NUM')?>&nbsp;</td>
						<td style="border: 1px solid #000;">&nbsp;<?php echo $tr->translate('BRANCH_NAME')?>&nbsp;</td>
						<td style="border: 1px solid #000;">&nbsp;<?php echo $tr->translate('EXPENSE_TITLE')?>&nbsp;</td>
						<td style="border: 1px solid #000;">&nbsp;<?php echo $tr->translate('NAME_ENTITLE')?>&nbsp;</td>
						<td style="border: 1px solid #000;">&nbsp;<?php echo $tr->translate('INVOICE_NO')?>&nbsp;</td>
						<td style="border: 1px solid #000;">&nbsp;<?php echo $tr->translate('TOTAL')?>&nbsp;</td>
						<td style="border: 1px solid #000;">&nbsp;<?php echo $tr->translate('Actual Payment Date')?>&nbsp;</td>
						<td style="border: 1px solid #000;">&nbsp;<?php echo $tr->translate('NOTE')?>&nbsp;</td>
						<td style="border: 1px solid #000;">&nbsp;<?php echo $tr->translate('USER')?>&nbsp;</td>
					</tr>
				</thead>
					 <style> td{padding:0 3px; }</style>
				<tbody>
				<?php $i=0;foreach($this->expense as $row){ $i++;?>
					<tr class="hover" style="font-size:12px; height: 20px;border: 1px solid #000; white-space: nowrap;" align="center" >
						<td align="center" style="border: 1px solid #000;">&nbsp;<?php echo $i;?>&nbsp;</td>
						<td style="border: 1px solid #000;">&nbsp;<?php echo $row['branch_name'];?>&nbsp;</td>
						<td style="border: 1px solid #000;text-align: left;"><span style="white-space:normal !important;font-family:'Khmer OS Content';line-height:17px;width:180px;!important; display: block;padding-left: 1px; padding: 2px 1px;"><?php echo $row['title'];?></span></td>
						<td align="center" style="border: 1px solid #000;">&nbsp;<span style="white-space:normal !important;width:120px;!important;"><?php echo $row['title_en'];?></span>&nbsp;</td>
						<td align="center" style="border: 1px solid #000;">&nbsp;<?php echo $row['invoice'];?>&nbsp;</td>
						<td align="right" style="border: 1px solid #000;background:#c6e2fb">&nbsp;<?php echo number_format($row['total_amount'],2);?><?php if($row['curr_type']==1){echo ' $';}else{echo ' រៀល​ ';}?>&nbsp;</td>
						<td align="center" style="border: 1px solid #000;">&nbsp;<?php echo date('d-M-Y',strtotime($row['for_date']));?></td>
						<td style="border: 1px solid #000;">&nbsp;<?php echo $row['desc'];?></td>
						<td align="center" style="border: 1px solid #000;font-size: 10px;">&nbsp;<?php echo $row['user_name'];?>&nbsp;</td>
					</tr>
						<?php 
							$total_expense_dollar = $total_expense_dollar + $row['total_amount'];
						?> 
					 <?php } ?>
					 <?php if(!empty($this->expense_po))foreach($this->expense_po as $row){ $i++;?>
					<tr class="hover" style="font-size:12px; height: 20px;border: 1px solid #000; white-space: nowrap;" align="center" >
						<td align="center" style="border: 1px solid #000;">&nbsp;<?php echo $i;?>&nbsp;</td>
						<td style="border: 1px solid #000;">&nbsp;<?php echo $row['branch_name'];?>&nbsp;</td>
						<td style="border: 1px solid #000;text-align: left;">&nbsp;<span style="width:120px;font-family:'Khmer OS Content'"></span><?php echo "ចំណាយលើអ្នកផ្គត់ផ្គង់(".$row['vendor'].")";?>&nbsp;</td>
						<td align="center" style="border: 1px solid #000;">&nbsp;<?php echo "Supplier's Expense(".$row['vendor'].")";?>&nbsp;</td>
						<td align="center" style="border: 1px solid #000;">&nbsp;<?php echo $row['receipt_no'];?>&nbsp;</td>
						<td align="right" style="border: 1px solid #000;background: #c6e2fb;"><?php echo number_format($row['total_paid'],2);?>&nbsp;$<?php //if($row['curr_type']==1){echo ' $';}else{echo ' រៀល​ ';}?>&nbsp;</td>
						<td align="center" style="border: 1px solid #000;">&nbsp;<?php echo date("d-M-Y",strtotime($row['expense_date']));?>&nbsp;</td>
						<td style="border: 1px solid #000;">&nbsp;<?php echo $row['remark'];?>&nbsp;</td>
						<td align="center" style="border: 1px solid #000;">&nbsp;<?php echo $row['user'];?>&nbsp;</td>
					</tr>
						<?php 
								$total_expense_dollar = $total_expense_dollar + $row['total_paid'];
						?> 
					 <?php } ?>
					 <tr class="hover" style="font-size:11px; height: 20px;border: 1px solid #000;" align="center" >
						<td style="border: 1px solid #fff;border-right: 1px solid #000;" colspan="7"></td>
						<td style="border: 1px solid #000; white-space: nowrap;">សរុបរួម/Grand Total</td>
						<td align="right" style="border: 1px solid #000;">&nbsp;<?php echo number_format($total_expense_dollar,2);?>&nbsp;</td>
					</tr>
					</tbody>
					</table>
				</td>
			</tr>
			<tr >
				<td align="center" width="25%">
					<span style=" font-size: 14px;"><?php echo $tr->translate("VERIFIED_BY"); ?></span>
				</td>
				<td  width="50%">
					&nbsp;
				</td>
				<td align="center"  width="25%">
					<span style=" font-size: 14px;text-align: right;"><?php echo $tr->translate("PREPARED_BY"); ?></span>
				</td>
			</tr>
		</table>
	</div>	
</div>
</div>
</div>
</div>
<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>
<?php 
	echo $this->render('printscript.phtml');
?>
