<?php 
$tr=Application_Form_FrmLanguages::getCurrentlanguage();
$brach_name =  $this->branch;
$row=$this->vendor_payment;
 
?>
<title><?php echo $tr->translate("Report Vendor Payment Detail");?></title>
<div class="row">
	<div class="col-md-12">
		<div class="portlet box blue">
			<div class="portlet-title">
				<div class="caption">
					<i class="fa fa-globe"></i><?php echo $tr->translate("Report Vendor Payment Detail");?>
				</div>
				<div class="btn-group pull-right">
						 <?php 	echo $this->render('printbutton.phtml');?>
				</div>
			</div>
            <div class="portlet-body form frmfilter">
				 
	<div style=" min-height:28cm; margin:0 auto; border: 1px dotted #ccc; padding:0px 0.2cm">
	<div id="divPrint" style="width: 100%;">
	<style>
		.style{
			line-height: 20px;font-size: 11px !important;
			font-family: 'Khmer OS Battambang';
		}
		ul{margin: 0;padding:0;}
		table tr td ul li{text-align: center;list-style: none;line-height: 25px; font-weight: bold;}
		th{padding: 5px;}
		.hover:hover{background: #ccc;}
	</style>
		<table style="font-family: 'Khmer OS Content'; width:100%;">
			<tbody>
			<tr>
		    	<td align="center">
		        	<table width="100%" style="font-family: 'Khmer OS Battambang';" cellpadding="0" cellpadding="0">
		            	<tbody><tr>
		                	<td width="25%" valign="top"><img src="<?php echo $this->baseUrl();?>/images/logo.jpg" height="85px"></td>
		                	<td width="50%" valign="top">
		                		<ul>
		                		    <li style="text-align:center; font-size:16px; font-family:'Khmer MEF2'"><?php echo $tr->translate("COMPANY_CUSTOMER");?></li>
		                			<li style="text-align:center; font-size:13px; font-family:'Khmer MEF2'"><?php echo $tr->translate("Report Vendor Payment Detail");?></li>
		                			<!-- <li style="text-align:center; font-size:13px;"><?php //echo date("d/m/Y",strtotime($this->rssearch['start_date']));?> ដល់ <?php //echo date("d/m/Y",strtotime($this->rssearch['end_date']));?></li> -->
		                		</ul>
		                	</td>
		                    <td width="25%"></td>
		                </tr> 
		                <tr>
		                	<td colspan="3" valign="top">
		                		<table width="100%" cellpadding="0" cellspacing="0">
		                			<tbody><tr>
		                				<td style="font-size: 11px;">
		                				    <ul>
					                		    <li style="text-align:left;"><?php echo $tr->translate("COMPANY_NAME");?>&nbsp;&nbsp;:&nbsp;<?php echo $row['com_name']?></li>
					                			<li style="text-align:left;"><?php echo $tr->translate("CON_NAME");?>&nbsp;&nbsp;:&nbsp;<?php echo $row['con_name']?></li>
					                			<li style="text-align:left;"><?php echo $tr->translate("CON_NUMBER");?>&nbsp;&nbsp;:&nbsp;<?php echo $row['phone_name']?></li>
					                		</ul>
		                				</td>
		                				<td width="65%"></td>
		                				<td style="font-size: 11px;">
		                				     <ul>
					                		    <li style="text-align:left;"><?php echo $tr->translate("BRANCH");?>&nbsp;&nbsp;:&nbsp;<?php echo $row['branch_name']?></li>
					                			<li style="text-align:left;"><?php echo $tr->translate("RECEIPT_NO");?>&nbsp;&nbsp;:&nbsp;<?php echo $row['receipt_no']?></li>
					                			<li style="text-align:left;"><?php echo $tr->translate("PAYMENT_DATE");?>&nbsp;&nbsp;:&nbsp;<?php echo date("d-M-Y",strtotime($row['expense_date']))?></li>
					                			<li style="text-align:left;"><?php echo $tr->translate("USER_NAME");?>&nbsp;&nbsp;:&nbsp;<?php echo $row['user_name']?></li>
					                		</ul>
		                				</td>
		                			</tr>
				                </tbody></table><br/>
				              </td>
				           </tr>   
		            </tbody></table>
		        </td>
		    </tr>
		    <tr>
		    	<td class="table2excel" id="exportExcel">
		            <table border="1" style="border-collapse:collapse;border:1px solid #000; font-size:12px;" width="100%" cellspacing="0">
		                 <tbody><tr bgcolor="#c1d0f3" class="style" align="center" style="font-weight:bold; line-height: 26px; font-size:12px; padding:1px 0px; white-space: nowrap; ">
		                    <td>&nbsp;<?php echo $tr->translate("NUM");?></td>
							 <td>&nbsp;<?php echo $tr->translate("INVOICE_NO");?></td>
							<td>&nbsp;<?php echo $tr->translate("GRAND_TOTAL");?></td>
							<td>&nbsp;<?php echo $tr->translate("PAID");?></td>
							<td >&nbsp;<?php echo $tr->translate("BALANCE");?></td>
							 
		                </tr>
		                <?php $num=1; 
		                $r_netotal = 0;$r_paid = 0; $r_balance = 0;
		                $d_netotal = 0;$d_paid = 0; $d_balance = 0;
		                $b_netotal = 0;$b_paid = 0; $b_balance = 0;
		                if(!empty($this->v_detail))foreach ($this->v_detail AS $index => $rs){?>
						<tr class='row-format<?php echo $num; $num=1-$num;?> hover' style="border:1px solid #000; white-space: nowrap;">
						   <td align="center" style="white-space: nowrap;">&nbsp;<?php echo $index+1?></td>
						   <td align="center" style="white-space: nowrap;font-family:'Open Sans', sans-serif;font-size: 12px; font-weight: bold;">&nbsp;<?php echo $rs["invoice_name"];?>&nbsp;</td>
						   <td align="right" style="white-space: nowrap;font-family:'Open Sans', sans-serif;font-size: 12px; font-weight: bold;">&nbsp;<?php echo number_format($rs["total"],2);?>&nbsp;</td>
						   <td align="right" style="white-space: nowrap;font-family:'Open Sans', sans-serif;font-size: 12px; font-weight: bold;">&nbsp;<?php echo number_format($rs["paid"],2);?>&nbsp;</td>
						   <td align="right" style="white-space: nowrap;font-family:'Open Sans', sans-serif;font-size: 12px; font-weight: bold;">&nbsp;<?php echo number_format($rs["balance"],2);?>&nbsp;</td>
						</tr>
						   <?php 
								$d_netotal = $d_netotal+$rs["total"];
								$d_paid = $d_paid+$rs["paid"];
								$d_balance = $d_balance+$rs["balance"];
                    }?>
		                </tbody>
		           </table>
		            <br>
		             <table border="1" style="border-collapse:collapse;border:1px solid #000; font-size:12px;" width="100%" cellspacing="0">
		                <tbody><tr height="30px;" bgcolor="#c1d0f3" class="style" align="center" style="floafont-weight:bold; line-height: 14px; font-size:12px; padding:2px 0px; ">
		                    <td><?php echo $tr->translate("CURRENCY_TYPE");?></td>
		                    <td><strong><?php echo $tr->translate("ALL_TOTAL");?></strong></td>
		                    <td><strong><?php echo $tr->translate("ALL_PAID");?></strong></td>
		                    <td><strong><?php echo $tr->translate("BALANCE");?></strong></td>
		                </tr>
		                 <tr class="style" style=" line-height: 24px; font-size:11px;">
		                    <td align="center">&nbsp;<?php echo $tr->translate("DOLLAR");?></td>
		                     <td align="right" style="font-family:'Open Sans', sans-serif;font-size: 12px; font-weight: bold;">&nbsp;<?php echo number_format($d_netotal,2);?>&nbsp;</td>
		                      <td align="right" style="font-family:'Open Sans', sans-serif;font-size: 12px; font-weight: bold;">&nbsp;<?php echo number_format($d_paid,2);?>&nbsp;</td>
		                    <td align="right" style="font-family:'Open Sans', sans-serif;font-size: 12px; font-weight: bold;">&nbsp;<?php echo number_format($d_netotal-$d_paid,2);?>&nbsp;</td>
		                 </tr>
		               </tbody>
		             </table>
		              <br>
		              <table align="center" width="100%">
						   <tbody><tr style="font-size: 11px;">
						        <th style="width:20%;text-align:center;  font-family:'Khmer MEF2'">យល់ព្រមដោយ</th>
						        <th></th>
						        <th style="width:20%;text-align:center; font-family:'Khmer MEF2'">ត្រួតពិនិត្យដោយ</th>
						        <th></th>
						        <th style="width:20%;text-align:center;font-family:'Khmer MEF2'">រៀបចំដោយ</th>
						   </tr>
						</tbody>
					</table>	
		    		</td>
		    	</tr>
			</tbody>
		</table>
		</div>
	  </div>		
	</div>
	 </div>
   </div>
</div>
<iframe name=print_frame width=0 height=0 frameborder=0 src=about:blank></iframe>
<script>
function doPrint() {var divToPrint = document.getElementById('divPrint');var htmlToPrint = '' +'<style type="text/css">' +'</style>';htmlToPrint += divToPrint.outerHTML;window.document.write(htmlToPrint);window.print();window.close();}
</script>
